<?php
// Med_Tech/includes/demo_data.php

/**
 * Demo Data Provider for Medical Technologist Portal
 * Tupi Municipal Hospital Laboratory Information Management System
 */

function getDemoPatients(): array
{
    return [
        [
            'id' => 'P-2026-0001',
            'name' => 'Juan Dela Cruz',
            'age' => 45,
            'gender' => 'Male',
            'contact' => '+63 917 123 4567',
            'blood_type' => 'O+',
            'room' => 'Room 204 (General Ward)',
            'doctor' => 'Dr. Michael Reyes, MD (Internal Medicine)',
            'diagnosis' => 'Community Acquired Pneumonia, Type 2 DM'
        ],
        [
            'id' => 'P-2026-0002',
            'name' => 'Maria Clara Santos',
            'age' => 32,
            'gender' => 'Female',
            'contact' => '+63 918 234 5678',
            'blood_type' => 'A+',
            'room' => 'Room 102 (OB-GYN)',
            'doctor' => 'Dr. Elena Villanueva, MD (Obstetrics)',
            'diagnosis' => 'Gravida 2 Para 1, 28 Weeks AOG'
        ],
        [
            'id' => 'P-2026-0003',
            'name' => 'Rodrigo Morales',
            'age' => 58,
            'gender' => 'Male',
            'contact' => '+63 919 345 6789',
            'blood_type' => 'B+',
            'room' => 'ICU Bed 03',
            'doctor' => 'Dr. Antonio Mendoza, MD (Cardiology)',
            'diagnosis' => 'Acute Coronary Syndrome, STEMI Post-PCI'
        ],
        [
            'id' => 'P-2026-0004',
            'name' => 'Angelica Mae Reyes',
            'age' => 24,
            'gender' => 'Female',
            'contact' => '+63 920 456 7890',
            'blood_type' => 'AB+',
            'room' => 'Outpatient Clinic 3',
            'doctor' => 'Dr. Sophia Ramos, MD (Endocrinology)',
            'diagnosis' => 'Hyperthyroidism under investigation'
        ],
        [
            'id' => 'P-2026-0005',
            'name' => 'Eduardo Dizon',
            'age' => 67,
            'gender' => 'Male',
            'contact' => '+63 921 567 8901',
            'blood_type' => 'O-',
            'room' => 'Room 312 (Nephrology)',
            'doctor' => 'Dr. Carlos Tan, MD (Nephrology)',
            'diagnosis' => 'Chronic Kidney Disease Stage 4'
        ],
        [
            'id' => 'P-2026-0006',
            'name' => 'Crisanto Valenzuela',
            'age' => 41,
            'gender' => 'Male',
            'contact' => '+63 922 678 9012',
            'blood_type' => 'A-',
            'room' => 'Room 208 (Internal Medicine)',
            'doctor' => 'Dr. Michael Reyes, MD (Internal Medicine)',
            'diagnosis' => 'Uncontrolled Hypertension, Dyslipidemia'
        ],
        [
            'id' => 'P-2026-0007',
            'name' => 'Kristine Joy Garcia',
            'age' => 29,
            'gender' => 'Female',
            'contact' => '+63 923 789 0123',
            'blood_type' => 'O+',
            'room' => 'ER Bed 06 (Emergency)',
            'doctor' => 'Dr. Gabriel Mercado, MD (Emergency Medicine)',
            'diagnosis' => 'Acute Appendicitis vs Pelvic Inflammatory'
        ],
        [
            'id' => 'P-2026-0008',
            'name' => 'Leandro Bautista',
            'age' => 52,
            'gender' => 'Male',
            'contact' => '+63 924 890 1234',
            'blood_type' => 'B-',
            'room' => 'Room 405 (Gastroenterology)',
            'doctor' => 'Dr. Victoria Gomez, MD (Gastroenterology)',
            'diagnosis' => 'Non-Alcoholic Fatty Liver Disease (NAFLD)'
        ],
        [
            'id' => 'P-2026-0009',
            'name' => 'Teresa May Aquino',
            'age' => 38,
            'gender' => 'Female',
            'contact' => '+63 925 901 2345',
            'blood_type' => 'A+',
            'room' => 'Room 110 (Surgery)',
            'doctor' => 'Dr. Rafael Cruz, MD (General Surgery)',
            'diagnosis' => 'Cholelithiasis with Chronic Cholecystitis'
        ],
        [
            'id' => 'P-2026-0010',
            'name' => 'Gabriel Mendoza',
            'age' => 63,
            'gender' => 'Male',
            'contact' => '+63 926 012 3456',
            'blood_type' => 'AB-',
            'room' => 'Room 304 (Pulmonology)',
            'doctor' => 'Dr. Luisa Fernandez, MD (Pulmonology)',
            'diagnosis' => 'COPD with Acute Exacerbation'
        ],
        [
            'id' => 'P-2026-0011',
            'name' => 'Rosanna Cortez',
            'age' => 49,
            'gender' => 'Female',
            'contact' => '+63 927 123 4567',
            'blood_type' => 'O+',
            'room' => 'Outpatient Clinic 1',
            'doctor' => 'Dr. Sophia Ramos, MD (Endocrinology)',
            'diagnosis' => 'Type 2 Diabetes Mellitus, Annual Workup'
        ],
        [
            'id' => 'P-2026-0012',
            'name' => 'Mark Anthony Ramos',
            'age' => 19,
            'gender' => 'Male',
            'contact' => '+63 928 234 5678',
            'blood_type' => 'B+',
            'room' => 'ER Bed 02 (Emergency)',
            'doctor' => 'Dr. Gabriel Mercado, MD (Emergency Medicine)',
            'diagnosis' => 'Dengue Fever Day 4 with Warning Signs'
        ],
        [
            'id' => 'P-2026-0013',
            'name' => 'Bernadette Cruz',
            'age' => 35,
            'gender' => 'Female',
            'contact' => '+63 929 345 6789',
            'blood_type' => 'A+',
            'room' => 'Room 214 (General Ward)',
            'doctor' => 'Dr. Michael Reyes, MD (Internal Medicine)',
            'diagnosis' => 'Urinary Tract Infection, Pyelonephritis'
        ],
        [
            'id' => 'P-2026-0014',
            'name' => 'Danilo Pascual',
            'age' => 71,
            'gender' => 'Male',
            'contact' => '+63 930 456 7890',
            'blood_type' => 'O+',
            'room' => 'Room 318 (Cardiology)',
            'doctor' => 'Dr. Antonio Mendoza, MD (Cardiology)',
            'diagnosis' => 'Congestive Heart Failure NYHA Class III'
        ],
        [
            'id' => 'P-2026-0015',
            'name' => 'Carmela Silang',
            'age' => 27,
            'gender' => 'Female',
            'contact' => '+63 931 567 8901',
            'blood_type' => 'B+',
            'room' => 'Outpatient Wellness Lab',
            'doctor' => 'Dr. Elena Villanueva, MD (Family Medicine)',
            'diagnosis' => 'Pre-Employment Medical Examination'
        ],
        [
            'id' => 'P-2026-0016',
            'name' => 'Ferdinand Ocampo',
            'age' => 54,
            'gender' => 'Male',
            'contact' => '+63 932 678 9012',
            'blood_type' => 'A+',
            'room' => 'Room 220 (Oncology)',
            'doctor' => 'Dr. Theresa Salazar, MD (Oncology)',
            'diagnosis' => 'Colorectal Carcinoma Post-Chemo Round 3'
        ],
        [
            'id' => 'P-2026-0017',
            'name' => 'Jasmine Flores',
            'age' => 8,
            'gender' => 'Female',
            'contact' => '+63 933 789 0123',
            'blood_type' => 'O+',
            'room' => 'Pediatrics Ward Bed 04',
            'doctor' => 'Dr. Manuel Roxas, MD (Pediatrics)',
            'diagnosis' => 'Viral Gastroenteritis with Mild Dehydration'
        ],
        [
            'id' => 'P-2026-0018',
            'name' => 'Renato Gutierrez',
            'age' => 48,
            'gender' => 'Male',
            'contact' => '+63 934 890 1234',
            'blood_type' => 'AB+',
            'room' => 'Room 408 (Surgery)',
            'doctor' => 'Dr. Rafael Cruz, MD (General Surgery)',
            'diagnosis' => 'Inguinal Hernia Pre-Operative Workup'
        ],
        [
            'id' => 'P-2026-0019',
            'name' => 'Patricia Lim',
            'age' => 31,
            'gender' => 'Female',
            'contact' => '+63 935 901 2345',
            'blood_type' => 'O-',
            'room' => 'Room 105 (OB-GYN)',
            'doctor' => 'Dr. Elena Villanueva, MD (Obstetrics)',
            'diagnosis' => 'Recurrent Pregnancy Loss Workup'
        ],
        [
            'id' => 'P-2026-0020',
            'name' => 'Arnel Del Rosario',
            'age' => 62,
            'gender' => 'Male',
            'contact' => '+63 936 012 3456',
            'blood_type' => 'B+',
            'room' => 'Dialysis Center Station 5',
            'doctor' => 'Dr. Carlos Tan, MD (Nephrology)',
            'diagnosis' => 'End Stage Renal Disease on Maintenance HD'
        ],
        [
            'id' => 'P-2026-0021',
            'name' => 'Maricris Santos-Bello',
            'age' => 39,
            'gender' => 'Female',
            'contact' => '+63 937 123 4567',
            'blood_type' => 'A+',
            'room' => 'Outpatient Clinic 2',
            'doctor' => 'Dr. Sophia Ramos, MD (Endocrinology)',
            'diagnosis' => 'Papillary Thyroid Carcinoma Post-Thyroidectomy'
        ],
        [
            'id' => 'P-2026-0022',
            'name' => 'Victor Emmanuel Sy',
            'age' => 46,
            'gender' => 'Male',
            'contact' => '+63 938 234 5678',
            'blood_type' => 'O+',
            'room' => 'Executive Checkup Suite',
            'doctor' => 'Dr. Michael Reyes, MD (Internal Medicine)',
            'diagnosis' => 'Executive Health Screening'
        ]
    ];
}

function getDemoTestCatalog(): array
{
    return [
        [
            'test_id' => 'TST-001',
            'test_name' => 'Complete Blood Count (CBC) with Platelet',
            'category' => 'Hematology',
            'specimen' => 'Whole Blood (EDTA - Lavender Top)',
            'volume' => '2.0 mL',
            'tat' => '1 - 2 Hours',
            'section' => 'Hematology Section',
            'price' => '₱ 380.00',
            'status' => 'Active',
            'description' => 'Automated differential measurement of RBC, WBC, Hemoglobin, Hematocrit, Platelets, and cell indices.'
        ],
        [
            'test_id' => 'TST-002',
            'test_name' => 'Routine Urinalysis (Automated & Microscopy)',
            'category' => 'Clinical Microscopy',
            'specimen' => 'Clean-catch Midstream Urine',
            'volume' => '15.0 mL',
            'tat' => '1 Hour',
            'section' => 'Microscopy Section',
            'price' => '₱ 190.00',
            'status' => 'Active',
            'description' => 'Physical, chemical dipstick analysis and microscopic sediment evaluation for casts, crystals, cells.'
        ],
        [
            'test_id' => 'TST-003',
            'test_name' => 'Fasting Blood Sugar (FBS)',
            'category' => 'Clinical Chemistry',
            'specimen' => 'Serum (SST - Gold/Red Top)',
            'volume' => '3.0 mL',
            'tat' => '2 Hours',
            'section' => 'Chemistry Section',
            'price' => '₱ 220.00',
            'status' => 'Active',
            'description' => 'Enzymatic determination of serum glucose concentration after 8-10 hour fast.'
        ],
        [
            'test_id' => 'TST-004',
            'test_name' => 'Lipid Profile Panel',
            'category' => 'Clinical Chemistry',
            'specimen' => 'Serum (SST - Gold Top)',
            'volume' => '4.0 mL',
            'tat' => '2 - 3 Hours',
            'section' => 'Chemistry Section',
            'price' => '₱ 850.00',
            'status' => 'Active',
            'description' => 'Quantitative measurement of Total Cholesterol, Triglycerides, HDL, LDL, and VLDL calculated ratios.'
        ],
        [
            'test_id' => 'TST-005',
            'test_name' => 'Liver Function Test (LFT) Comprehensive',
            'category' => 'Clinical Chemistry',
            'specimen' => 'Serum (SST - Gold Top)',
            'volume' => '4.0 mL',
            'tat' => '3 Hours',
            'section' => 'Chemistry Section',
            'price' => '₱ 1,150.00',
            'status' => 'Active',
            'description' => 'Assessment of SGPT/ALT, SGOT/AST, Alkaline Phosphatase, Total Bilirubin, Direct/Indirect Bilirubin, Total Protein, Albumin, Globulin.'
        ],
        [
            'test_id' => 'TST-006',
            'test_name' => 'Kidney Function Panel (BUN, Creatinine, eGFR, Uric Acid)',
            'category' => 'Clinical Chemistry',
            'specimen' => 'Serum (SST - Gold Top)',
            'volume' => '3.0 mL',
            'tat' => '2 Hours',
            'section' => 'Chemistry Section',
            'price' => '₱ 720.00',
            'status' => 'Active',
            'description' => 'Renal clearance and nitrogenous waste assessment including Creatinine, Blood Urea Nitrogen, and CKD-EPI eGFR.'
        ],
        [
            'test_id' => 'TST-007',
            'test_name' => 'Serum Electrolytes (Na+, K+, Cl-, Ca2+, iCa)',
            'category' => 'Clinical Chemistry',
            'specimen' => 'Serum / Lithium Heparin Plasma',
            'volume' => '3.0 mL',
            'tat' => '1 - 2 Hours',
            'section' => 'Chemistry Section',
            'price' => '₱ 780.00',
            'status' => 'Active',
            'description' => 'Direct ISE quantification of sodium, potassium, chloride, ionized calcium, and total calcium.'
        ],
        [
            'test_id' => 'TST-008',
            'test_name' => 'Hemoglobin A1c (HbA1c / Glycated Hemoglobin)',
            'category' => 'Hematology / Special Chem',
            'specimen' => 'Whole Blood (EDTA - Lavender Top)',
            'volume' => '2.0 mL',
            'tat' => '2 Hours',
            'section' => 'Special Chemistry',
            'price' => '₱ 680.00',
            'status' => 'Active',
            'description' => 'HPLC determination of average 3-month glycation index in diabetic monitoring.'
        ],
        [
            'test_id' => 'TST-009',
            'test_name' => 'Dengue Duo Rapid Test (NS1 Ag + IgG/IgM Ab)',
            'category' => 'Immunology / Serology',
            'specimen' => 'Serum / EDTA Plasma',
            'volume' => '2.0 mL',
            'tat' => '45 Minutes',
            'section' => 'Serology Section',
            'price' => '₱ 950.00',
            'status' => 'Active',
            'description' => 'Immunochromatographic qualitative detection of Dengue virus NS1 antigen and specific antibodies.'
        ],
        [
            'test_id' => 'TST-010',
            'test_name' => 'Thyroid Profile Comprehensive (FT3, FT4, TSH)',
            'category' => 'Immunology / Endocrinology',
            'specimen' => 'Serum (SST - Gold Top)',
            'volume' => '4.0 mL',
            'tat' => '3 - 4 Hours',
            'section' => 'Immunology Section',
            'price' => '₱ 1,450.00',
            'status' => 'Active',
            'description' => 'Chemiluminescent immunoassay for Free Triiodothyronine, Free Thyroxine, and Thyroid Stimulating Hormone.'
        ],
        [
            'test_id' => 'TST-011',
            'test_name' => 'ABO Blood Typing & Rh Factor Confirmation',
            'category' => 'Immunohematology / Blood Bank',
            'specimen' => 'Whole Blood (EDTA - Pink/Lavender)',
            'volume' => '3.0 mL',
            'tat' => '1 Hour',
            'section' => 'Blood Bank Section',
            'price' => '₱ 320.00',
            'status' => 'Active',
            'description' => 'Forward and reverse grouping with Rh(D) typing by column agglutination / tube method.'
        ],
        [
            'test_id' => 'TST-012',
            'test_name' => 'COVID-19 & Multiplex Respiratory Viral Panel',
            'category' => 'Molecular Diagnostics',
            'specimen' => 'Nasopharyngeal / Oropharyngeal Swab (VTM)',
            'volume' => '1 Swab in VTM',
            'tat' => '4 - 6 Hours',
            'section' => 'Molecular Section',
            'price' => '₱ 2,400.00',
            'status' => 'Active',
            'description' => 'Real-Time RT-PCR for SARS-CoV-2, Influenza A, Influenza B, and RSV detection.'
        ]
    ];
}

function getDemoReferenceRanges(): array
{
    return [
        ['test' => 'Complete Blood Count', 'parameter' => 'Hemoglobin', 'gender' => 'Male', 'age_range' => '18–65', 'min' => 13.0, 'max' => 17.5, 'unit' => 'g/dL', 'crit_low' => 7.0, 'crit_high' => 20.0],
        ['test' => 'Complete Blood Count', 'parameter' => 'Hemoglobin', 'gender' => 'Female', 'age_range' => '18–65', 'min' => 12.0, 'max' => 15.5, 'unit' => 'g/dL', 'crit_low' => 7.0, 'crit_high' => 19.0],
        ['test' => 'Complete Blood Count', 'parameter' => 'Hematocrit', 'gender' => 'Male', 'age_range' => '18–65', 'min' => 40.0, 'max' => 52.0, 'unit' => '%', 'crit_low' => 21.0, 'crit_high' => 60.0],
        ['test' => 'Complete Blood Count', 'parameter' => 'Hematocrit', 'gender' => 'Female', 'age_range' => '18–65', 'min' => 36.0, 'max' => 48.0, 'unit' => '%', 'crit_low' => 21.0, 'crit_high' => 55.0],
        ['test' => 'Complete Blood Count', 'parameter' => 'WBC Count', 'gender' => 'All', 'age_range' => 'Adult', 'min' => 4.5, 'max' => 11.0, 'unit' => 'x10⁹/L', 'crit_low' => 2.0, 'crit_high' => 30.0],
        ['test' => 'Complete Blood Count', 'parameter' => 'RBC Count', 'gender' => 'Male', 'age_range' => 'Adult', 'min' => 4.5, 'max' => 5.9, 'unit' => 'x10¹²/L', 'crit_low' => 2.5, 'crit_high' => 7.0],
        ['test' => 'Complete Blood Count', 'parameter' => 'RBC Count', 'gender' => 'Female', 'age_range' => 'Adult', 'min' => 4.0, 'max' => 5.2, 'unit' => 'x10¹²/L', 'crit_low' => 2.5, 'crit_high' => 6.5],
        ['test' => 'Complete Blood Count', 'parameter' => 'Platelet Count', 'gender' => 'All', 'age_range' => 'Adult', 'min' => 150.0, 'max' => 450.0, 'unit' => 'x10⁹/L', 'crit_low' => 50.0, 'crit_high' => 1000.0],
        ['test' => 'Complete Blood Count', 'parameter' => 'Segmenters / Neutrophils', 'gender' => 'All', 'age_range' => 'Adult', 'min' => 50.0, 'max' => 70.0, 'unit' => '%', 'crit_low' => 20.0, 'crit_high' => 90.0],
        ['test' => 'Complete Blood Count', 'parameter' => 'Lymphocytes', 'gender' => 'All', 'age_range' => 'Adult', 'min' => 20.0, 'max' => 40.0, 'unit' => '%', 'crit_low' => 10.0, 'crit_high' => 70.0],
        ['test' => 'Complete Blood Count', 'parameter' => 'Monocytes', 'gender' => 'All', 'age_range' => 'Adult', 'min' => 2.0, 'max' => 8.0, 'unit' => '%', 'crit_low' => 0.0, 'crit_high' => 20.0],
        ['test' => 'Complete Blood Count', 'parameter' => 'Eosinophils', 'gender' => 'All', 'age_range' => 'Adult', 'min' => 1.0, 'max' => 4.0, 'unit' => '%', 'crit_low' => 0.0, 'crit_high' => 15.0],
        ['test' => 'Complete Blood Count', 'parameter' => 'Basophils', 'gender' => 'All', 'age_range' => 'Adult', 'min' => 0.0, 'max' => 1.0, 'unit' => '%', 'crit_low' => 0.0, 'crit_high' => 5.0],
        
        // Chemistry
        ['test' => 'Fasting Blood Sugar', 'parameter' => 'Glucose (FBS)', 'gender' => 'All', 'age_range' => 'Adult', 'min' => 70.0, 'max' => 100.0, 'unit' => 'mg/dL', 'crit_low' => 45.0, 'crit_high' => 400.0],
        ['test' => 'Lipid Profile', 'parameter' => 'Total Cholesterol', 'gender' => 'All', 'age_range' => 'Adult', 'min' => 0.0, 'max' => 200.0, 'unit' => 'mg/dL', 'crit_low' => 0.0, 'crit_high' => 350.0],
        ['test' => 'Lipid Profile', 'parameter' => 'Triglycerides', 'gender' => 'All', 'age_range' => 'Adult', 'min' => 0.0, 'max' => 150.0, 'unit' => 'mg/dL', 'crit_low' => 0.0, 'crit_high' => 500.0],
        ['test' => 'Lipid Profile', 'parameter' => 'HDL Cholesterol (Good)', 'gender' => 'Male', 'age_range' => 'Adult', 'min' => 40.0, 'max' => 90.0, 'unit' => 'mg/dL', 'crit_low' => 20.0, 'crit_high' => 120.0],
        ['test' => 'Lipid Profile', 'parameter' => 'HDL Cholesterol (Good)', 'gender' => 'Female', 'age_range' => 'Adult', 'min' => 50.0, 'max' => 90.0, 'unit' => 'mg/dL', 'crit_low' => 25.0, 'crit_high' => 120.0],
        ['test' => 'Lipid Profile', 'parameter' => 'LDL Cholesterol (Bad)', 'gender' => 'All', 'age_range' => 'Adult', 'min' => 0.0, 'max' => 100.0, 'unit' => 'mg/dL', 'crit_low' => 0.0, 'crit_high' => 190.0],
        ['test' => 'Kidney Function Panel', 'parameter' => 'Blood Urea Nitrogen (BUN)', 'gender' => 'All', 'age_range' => 'Adult', 'min' => 7.0, 'max' => 20.0, 'unit' => 'mg/dL', 'crit_low' => 3.0, 'crit_high' => 80.0],
        ['test' => 'Kidney Function Panel', 'parameter' => 'Serum Creatinine', 'gender' => 'Male', 'age_range' => 'Adult', 'min' => 0.7, 'max' => 1.3, 'unit' => 'mg/dL', 'crit_low' => 0.4, 'crit_high' => 5.0],
        ['test' => 'Kidney Function Panel', 'parameter' => 'Serum Creatinine', 'gender' => 'Female', 'age_range' => 'Adult', 'min' => 0.5, 'max' => 1.1, 'unit' => 'mg/dL', 'crit_low' => 0.3, 'crit_high' => 4.5],
        ['test' => 'Kidney Function Panel', 'parameter' => 'Serum Uric Acid', 'gender' => 'Male', 'age_range' => 'Adult', 'min' => 3.5, 'max' => 7.2, 'unit' => 'mg/dL', 'crit_low' => 1.5, 'crit_high' => 12.0],
        ['test' => 'Kidney Function Panel', 'parameter' => 'Serum Uric Acid', 'gender' => 'Female', 'age_range' => 'Adult', 'min' => 2.6, 'max' => 6.0, 'unit' => 'mg/dL', 'crit_low' => 1.5, 'crit_high' => 10.0],
        ['test' => 'Liver Function Test', 'parameter' => 'SGPT / ALT', 'gender' => 'All', 'age_range' => 'Adult', 'min' => 0.0, 'max' => 45.0, 'unit' => 'U/L', 'crit_low' => 0.0, 'crit_high' => 300.0],
        ['test' => 'Liver Function Test', 'parameter' => 'SGOT / AST', 'gender' => 'All', 'age_range' => 'Adult', 'min' => 0.0, 'max' => 40.0, 'unit' => 'U/L', 'crit_low' => 0.0, 'crit_high' => 300.0],
        ['test' => 'Electrolytes', 'parameter' => 'Serum Potassium (K+)', 'gender' => 'All', 'age_range' => 'Adult', 'min' => 3.5, 'max' => 5.1, 'unit' => 'mmol/L', 'crit_low' => 2.8, 'crit_high' => 6.2],
        ['test' => 'Electrolytes', 'parameter' => 'Serum Sodium (Na+)', 'gender' => 'All', 'age_range' => 'Adult', 'min' => 135.0, 'max' => 145.0, 'unit' => 'mmol/L', 'crit_low' => 120.0, 'crit_high' => 160.0]
    ];
}

function getDemoLabRequests(): array
{
    return [
        [
            'request_id' => 'LAB-2026-001',
            'patient_id' => 'P-2026-0001',
            'patient_name' => 'Juan Dela Cruz',
            'age' => 45,
            'gender' => 'Male',
            'doctor' => 'Dr. Michael Reyes',
            'test' => 'Complete Blood Count (CBC)',
            'test_id' => 'TST-001',
            'priority' => 'High',
            'date' => '2026-08-28',
            'time' => '08:15 AM',
            'status' => 'Processing',
            'sample_id' => 'SMP-2026-00124',
            'clinical_notes' => 'Patient febrile T: 38.6°C. Monitor leukocytosis and left shift.',
            'category' => 'Hematology'
        ],
        [
            'request_id' => 'LAB-2026-002',
            'patient_id' => 'P-2026-0003',
            'patient_name' => 'Rodrigo Morales',
            'age' => 58,
            'gender' => 'Male',
            'doctor' => 'Dr. Antonio Mendoza',
            'test' => 'Serum Electrolytes (Na+, K+, Cl-)',
            'test_id' => 'TST-007',
            'priority' => 'STAT',
            'date' => '2026-08-28',
            'time' => '08:30 AM',
            'status' => 'Pending',
            'sample_id' => 'SMP-2026-00125',
            'clinical_notes' => 'ICU cardiac monitoring; evaluate potassium level immediately post-diuretic bolus.',
            'category' => 'Clinical Chemistry'
        ],
        [
            'request_id' => 'LAB-2026-003',
            'patient_id' => 'P-2026-0004',
            'patient_name' => 'Angelica Mae Reyes',
            'age' => 24,
            'gender' => 'Female',
            'doctor' => 'Dr. Sophia Ramos',
            'test' => 'Thyroid Profile Comprehensive',
            'test_id' => 'TST-010',
            'priority' => 'Routine',
            'date' => '2026-08-28',
            'time' => '08:45 AM',
            'status' => 'Received',
            'sample_id' => 'SMP-2026-00126',
            'clinical_notes' => 'Workup for resting tachycardia, tremors, and weight loss.',
            'category' => 'Immunology'
        ],
        [
            'request_id' => 'LAB-2026-004',
            'patient_id' => 'P-2026-0005',
            'patient_name' => 'Eduardo Dizon',
            'age' => 67,
            'gender' => 'Male',
            'doctor' => 'Dr. Carlos Tan',
            'test' => 'Kidney Function Panel',
            'test_id' => 'TST-006',
            'priority' => 'Urgent',
            'date' => '2026-08-28',
            'time' => '09:00 AM',
            'status' => 'Processing',
            'sample_id' => 'SMP-2026-00127',
            'clinical_notes' => 'CKD stage 4 routine pre-dialysis evaluation; check BUN/Creatinine/eGFR.',
            'category' => 'Clinical Chemistry'
        ],
        [
            'request_id' => 'LAB-2026-005',
            'patient_id' => 'P-2026-0007',
            'patient_name' => 'Kristine Joy Garcia',
            'age' => 29,
            'gender' => 'Female',
            'doctor' => 'Dr. Gabriel Mercado',
            'test' => 'Routine Urinalysis',
            'test_id' => 'TST-002',
            'priority' => 'Urgent',
            'date' => '2026-08-28',
            'time' => '09:12 AM',
            'status' => 'Completed',
            'sample_id' => 'SMP-2026-00128',
            'clinical_notes' => 'Right lower quadrant tenderness; rule out pyuria and hematuria.',
            'category' => 'Clinical Microscopy'
        ],
        [
            'request_id' => 'LAB-2026-006',
            'patient_id' => 'P-2026-0012',
            'patient_name' => 'Mark Anthony Ramos',
            'age' => 19,
            'gender' => 'Male',
            'doctor' => 'Dr. Gabriel Mercado',
            'test' => 'Dengue Duo Rapid Test',
            'test_id' => 'TST-009',
            'priority' => 'STAT',
            'date' => '2026-08-28',
            'time' => '09:25 AM',
            'status' => 'Completed',
            'sample_id' => 'SMP-2026-00129',
            'clinical_notes' => 'High-grade fever day 4 with petechiae. STAT NS1 and antibody test.',
            'category' => 'Immunology'
        ],
        [
            'request_id' => 'LAB-2026-007',
            'patient_id' => 'P-2026-0006',
            'patient_name' => 'Crisanto Valenzuela',
            'age' => 41,
            'gender' => 'Male',
            'doctor' => 'Dr. Michael Reyes',
            'test' => 'Lipid Profile Panel',
            'test_id' => 'TST-004',
            'priority' => 'Routine',
            'date' => '2026-08-28',
            'time' => '09:40 AM',
            'status' => 'Completed',
            'sample_id' => 'SMP-2026-00130',
            'clinical_notes' => '12-hour fasting confirmed. Cardiovascular risk reassessment.',
            'category' => 'Clinical Chemistry'
        ],
        [
            'request_id' => 'LAB-2026-008',
            'patient_id' => 'P-2026-0008',
            'patient_name' => 'Leandro Bautista',
            'age' => 52,
            'gender' => 'Male',
            'doctor' => 'Dr. Victoria Gomez',
            'test' => 'Liver Function Test (LFT)',
            'test_id' => 'TST-005',
            'priority' => 'Routine',
            'date' => '2026-08-28',
            'time' => '09:50 AM',
            'status' => 'Processing',
            'sample_id' => 'SMP-2026-00131',
            'clinical_notes' => 'Monitor transaminases post-statin initiation.',
            'category' => 'Clinical Chemistry'
        ],
        [
            'request_id' => 'LAB-2026-009',
            'patient_id' => 'P-2026-0002',
            'patient_name' => 'Maria Clara Santos',
            'age' => 32,
            'gender' => 'Female',
            'doctor' => 'Dr. Elena Villanueva',
            'test' => 'Complete Blood Count (CBC)',
            'test_id' => 'TST-001',
            'priority' => 'Routine',
            'date' => '2026-08-28',
            'time' => '10:00 AM',
            'status' => 'Completed',
            'sample_id' => 'SMP-2026-00132',
            'clinical_notes' => 'Third trimester anemia checkup.',
            'category' => 'Hematology'
        ],
        [
            'request_id' => 'LAB-2026-010',
            'patient_id' => 'P-2026-0011',
            'patient_name' => 'Rosanna Cortez',
            'age' => 49,
            'gender' => 'Female',
            'doctor' => 'Dr. Sophia Ramos',
            'test' => 'Hemoglobin A1c (HbA1c)',
            'test_id' => 'TST-008',
            'priority' => 'Routine',
            'date' => '2026-08-28',
            'time' => '10:15 AM',
            'status' => 'Pending',
            'sample_id' => 'SMP-2026-00133',
            'clinical_notes' => 'Quarterly glycemic control audit for Type 2 DM.',
            'category' => 'Hematology'
        ],
        [
            'request_id' => 'LAB-2026-011',
            'patient_id' => 'P-2026-0009',
            'patient_name' => 'Teresa May Aquino',
            'age' => 38,
            'gender' => 'Female',
            'doctor' => 'Dr. Rafael Cruz',
            'test' => 'ABO Blood Typing & Rh Factor',
            'test_id' => 'TST-011',
            'priority' => 'Urgent',
            'date' => '2026-08-28',
            'time' => '10:30 AM',
            'status' => 'Received',
            'sample_id' => 'SMP-2026-00134',
            'clinical_notes' => 'Pre-operative crossmatch preparation for laparoscopic cholecystectomy.',
            'category' => 'Blood Bank'
        ],
        [
            'request_id' => 'LAB-2026-012',
            'patient_id' => 'P-2026-0010',
            'patient_name' => 'Gabriel Mendoza',
            'age' => 63,
            'gender' => 'Male',
            'doctor' => 'Dr. Luisa Fernandez',
            'test' => 'COVID-19 & Respiratory Panel',
            'test_id' => 'TST-012',
            'priority' => 'STAT',
            'date' => '2026-08-28',
            'time' => '10:45 AM',
            'status' => 'Processing',
            'sample_id' => 'SMP-2026-00135',
            'clinical_notes' => 'Severe dyspnea and productive cough; isolate while waiting for viral PCR.',
            'category' => 'Molecular'
        ],
        [
            'request_id' => 'LAB-2026-013',
            'patient_id' => 'P-2026-0013',
            'patient_name' => 'Bernadette Cruz',
            'age' => 35,
            'gender' => 'Female',
            'doctor' => 'Dr. Michael Reyes',
            'test' => 'Routine Urinalysis',
            'test_id' => 'TST-002',
            'priority' => 'Routine',
            'date' => '2026-08-28',
            'time' => '11:00 AM',
            'status' => 'Completed',
            'sample_id' => 'SMP-2026-00136',
            'clinical_notes' => 'Dysuria and flank discomfort.',
            'category' => 'Clinical Microscopy'
        ],
        [
            'request_id' => 'LAB-2026-014',
            'patient_id' => 'P-2026-0014',
            'patient_name' => 'Danilo Pascual',
            'age' => 71,
            'gender' => 'Male',
            'doctor' => 'Dr. Antonio Mendoza',
            'test' => 'Kidney Function Panel',
            'test_id' => 'TST-006',
            'priority' => 'Urgent',
            'date' => '2026-08-28',
            'time' => '11:15 AM',
            'status' => 'Pending',
            'sample_id' => 'SMP-2026-00137',
            'clinical_notes' => 'CHF exacerbation; monitor cardiorenal interaction.',
            'category' => 'Clinical Chemistry'
        ],
        [
            'request_id' => 'LAB-2026-015',
            'patient_id' => 'P-2026-0015',
            'patient_name' => 'Carmela Silang',
            'age' => 27,
            'gender' => 'Female',
            'doctor' => 'Dr. Elena Villanueva',
            'test' => 'Complete Blood Count (CBC)',
            'test_id' => 'TST-001',
            'priority' => 'Routine',
            'date' => '2026-08-28',
            'time' => '11:30 AM',
            'status' => 'Completed',
            'sample_id' => 'SMP-2026-00138',
            'clinical_notes' => 'Routine pre-employment package requirement.',
            'category' => 'Hematology'
        ],
        [
            'request_id' => 'LAB-2026-016',
            'patient_id' => 'P-2026-0016',
            'patient_name' => 'Ferdinand Ocampo',
            'age' => 54,
            'gender' => 'Male',
            'doctor' => 'Dr. Theresa Salazar',
            'test' => 'Complete Blood Count (CBC)',
            'test_id' => 'TST-001',
            'priority' => 'Urgent',
            'date' => '2026-08-28',
            'time' => '11:45 AM',
            'status' => 'Received',
            'sample_id' => 'SMP-2026-00139',
            'clinical_notes' => 'Post-chemo nadir monitoring; check ANC (Absolute Neutrophil Count).',
            'category' => 'Hematology'
        ],
        [
            'request_id' => 'LAB-2026-017',
            'patient_id' => 'P-2026-0017',
            'patient_name' => 'Jasmine Flores',
            'age' => 8,
            'gender' => 'Female',
            'doctor' => 'Dr. Manuel Roxas',
            'test' => 'Serum Electrolytes (Na+, K+, Cl-)',
            'test_id' => 'TST-007',
            'priority' => 'Urgent',
            'date' => '2026-08-28',
            'time' => '12:00 PM',
            'status' => 'Pending',
            'sample_id' => 'SMP-2026-00140',
            'clinical_notes' => 'Pediatric dehydration assessment.',
            'category' => 'Clinical Chemistry'
        ],
        [
            'request_id' => 'LAB-2026-018',
            'patient_id' => 'P-2026-0018',
            'patient_name' => 'Renato Gutierrez',
            'age' => 48,
            'gender' => 'Male',
            'doctor' => 'Dr. Rafael Cruz',
            'test' => 'Fasting Blood Sugar (FBS)',
            'test_id' => 'TST-003',
            'priority' => 'Routine',
            'date' => '2026-08-28',
            'time' => '12:15 PM',
            'status' => 'Completed',
            'sample_id' => 'SMP-2026-00141',
            'clinical_notes' => 'Elective pre-op clearance.',
            'category' => 'Clinical Chemistry'
        ],
        [
            'request_id' => 'LAB-2026-019',
            'patient_id' => 'P-2026-0019',
            'patient_name' => 'Patricia Lim',
            'age' => 31,
            'gender' => 'Female',
            'doctor' => 'Dr. Elena Villanueva',
            'test' => 'Thyroid Profile Comprehensive',
            'test_id' => 'TST-010',
            'priority' => 'Routine',
            'date' => '2026-08-28',
            'time' => '12:30 PM',
            'status' => 'Pending',
            'sample_id' => 'SMP-2026-00142',
            'clinical_notes' => 'Endocrine fertility clearance.',
            'category' => 'Immunology'
        ],
        [
            'request_id' => 'LAB-2026-020',
            'patient_id' => 'P-2026-0020',
            'patient_name' => 'Arnel Del Rosario',
            'age' => 62,
            'gender' => 'Male',
            'doctor' => 'Dr. Carlos Tan',
            'test' => 'Serum Electrolytes (Na+, K+, Cl-)',
            'test_id' => 'TST-007',
            'priority' => 'STAT',
            'date' => '2026-08-28',
            'time' => '12:45 PM',
            'status' => 'Processing',
            'sample_id' => 'SMP-2026-00143',
            'clinical_notes' => 'Pre-hemodialysis hyperkalemia screen.',
            'category' => 'Clinical Chemistry'
        ],
        [
            'request_id' => 'LAB-2026-021',
            'patient_id' => 'P-2026-0021',
            'patient_name' => 'Maricris Santos-Bello',
            'age' => 39,
            'gender' => 'Female',
            'doctor' => 'Dr. Sophia Ramos',
            'test' => 'Thyroid Profile Comprehensive',
            'test_id' => 'TST-010',
            'priority' => 'Routine',
            'date' => '2026-08-28',
            'time' => '01:00 PM',
            'status' => 'Received',
            'sample_id' => 'SMP-2026-00144',
            'clinical_notes' => 'Levothyroxine suppression dose monitoring.',
            'category' => 'Immunology'
        ],
        [
            'request_id' => 'LAB-2026-022',
            'patient_id' => 'P-2026-0022',
            'patient_name' => 'Victor Emmanuel Sy',
            'age' => 46,
            'gender' => 'Male',
            'doctor' => 'Dr. Michael Reyes',
            'test' => 'Lipid Profile Panel',
            'test_id' => 'TST-004',
            'priority' => 'Routine',
            'date' => '2026-08-28',
            'time' => '01:15 PM',
            'status' => 'Completed',
            'sample_id' => 'SMP-2026-00145',
            'clinical_notes' => 'Annual corporate executive wellness package.',
            'category' => 'Clinical Chemistry'
        ]
    ];
}

function getDemoSamples(): array
{
    return [
        [
            'sample_id' => 'SMP-2026-00124',
            'request_id' => 'LAB-2026-001',
            'patient_name' => 'Juan Dela Cruz',
            'patient_id' => 'P-2026-0001',
            'test' => 'Complete Blood Count (CBC)',
            'sample_type' => 'Whole Blood (EDTA)',
            'collection_date' => '2026-08-28',
            'collection_time' => '08:20 AM',
            'collected_by' => 'Nurse Maria Santos, RN',
            'condition' => 'Acceptable (Non-hemolyzed)',
            'status' => 'Processing',
            'stage_index' => 2, // 0: Collected, 1: Received, 2: Processing, 3: For Verification, 4: Completed
            'section' => 'Hematology Section',
            'rack_location' => 'RACK-HEM-A04',
            'notes' => 'Sample loaded onto Sysmex XN-1000 automated analyzer.'
        ],
        [
            'sample_id' => 'SMP-2026-00125',
            'request_id' => 'LAB-2026-002',
            'patient_name' => 'Rodrigo Morales',
            'patient_id' => 'P-2026-0003',
            'test' => 'Serum Electrolytes (Na+, K+, Cl-)',
            'sample_type' => 'Serum (SST)',
            'collection_date' => '2026-08-28',
            'collection_time' => '08:35 AM',
            'collected_by' => 'Nurse Juan Gomez, RN',
            'condition' => 'Acceptable',
            'status' => 'Collected',
            'stage_index' => 0,
            'section' => 'Chemistry Section',
            'rack_location' => 'RECEPTION-TRAY-1',
            'notes' => 'STAT transit from ICU.'
        ],
        [
            'sample_id' => 'SMP-2026-00126',
            'request_id' => 'LAB-2026-003',
            'patient_name' => 'Angelica Mae Reyes',
            'patient_id' => 'P-2026-0004',
            'test' => 'Thyroid Profile Comprehensive',
            'sample_type' => 'Serum (SST)',
            'collection_date' => '2026-08-28',
            'collection_time' => '08:50 AM',
            'collected_by' => 'MedTech Robert Santos, RMT',
            'condition' => 'Acceptable',
            'status' => 'Received',
            'stage_index' => 1,
            'section' => 'Immunology Section',
            'rack_location' => 'CENTRIFUGE-BAY-2',
            'notes' => 'Centrifuged at 3000 RPM for 10 mins.'
        ],
        [
            'sample_id' => 'SMP-2026-00127',
            'request_id' => 'LAB-2026-004',
            'patient_name' => 'Eduardo Dizon',
            'patient_id' => 'P-2026-0005',
            'test' => 'Kidney Function Panel',
            'sample_type' => 'Serum (SST)',
            'collection_date' => '2026-08-28',
            'collection_time' => '09:05 AM',
            'collected_by' => 'Nurse Maria Santos, RN',
            'condition' => 'Acceptable',
            'status' => 'Processing',
            'stage_index' => 2,
            'section' => 'Chemistry Section',
            'rack_location' => 'COBAS-C501-SLOT-12',
            'notes' => 'In photometric measurement cycle.'
        ],
        [
            'sample_id' => 'SMP-2026-00128',
            'request_id' => 'LAB-2026-005',
            'patient_name' => 'Kristine Joy Garcia',
            'patient_id' => 'P-2026-0007',
            'test' => 'Routine Urinalysis',
            'sample_type' => 'Clean-catch Urine',
            'collection_date' => '2026-08-28',
            'collection_time' => '09:15 AM',
            'collected_by' => 'Patient / Verified Nurse Jane',
            'condition' => 'Acceptable',
            'status' => 'Completed',
            'stage_index' => 4,
            'section' => 'Microscopy Section',
            'rack_location' => 'ARCHIVE-MIC-28A',
            'notes' => 'Microscopic sediment confirmed. Report finalized.'
        ],
        [
            'sample_id' => 'SMP-2026-00129',
            'request_id' => 'LAB-2026-006',
            'patient_name' => 'Mark Anthony Ramos',
            'patient_id' => 'P-2026-0012',
            'test' => 'Dengue Duo Rapid Test',
            'sample_type' => 'Serum',
            'collection_date' => '2026-08-28',
            'collection_time' => '09:30 AM',
            'collected_by' => 'MedTech Robert Santos, RMT',
            'condition' => 'Acceptable',
            'status' => 'Completed',
            'stage_index' => 4,
            'section' => 'Serology Section',
            'rack_location' => 'ARCHIVE-SER-08',
            'notes' => 'Dengue NS1 Ag Reactive verified.'
        ],
        [
            'sample_id' => 'SMP-2026-00130',
            'request_id' => 'LAB-2026-007',
            'patient_name' => 'Crisanto Valenzuela',
            'patient_id' => 'P-2026-0006',
            'test' => 'Lipid Profile Panel',
            'sample_type' => 'Serum (SST)',
            'collection_date' => '2026-08-28',
            'collection_time' => '09:45 AM',
            'collected_by' => 'MedTech Robert Santos, RMT',
            'condition' => 'Acceptable (Mild lipemia)',
            'status' => 'For Verification',
            'stage_index' => 3,
            'section' => 'Chemistry Section',
            'rack_location' => 'CHEM-VERIFY-TRAY',
            'notes' => 'Elevated triglycerides calculated. Ready for pathologist signature.'
        ],
        [
            'sample_id' => 'SMP-2026-00131',
            'request_id' => 'LAB-2026-008',
            'patient_name' => 'Leandro Bautista',
            'patient_id' => 'P-2026-0008',
            'test' => 'Liver Function Test (LFT)',
            'sample_type' => 'Serum (SST)',
            'collection_date' => '2026-08-28',
            'collection_time' => '09:55 AM',
            'collected_by' => 'Nurse Teresa Diaz, RN',
            'condition' => 'Acceptable',
            'status' => 'Processing',
            'stage_index' => 2,
            'section' => 'Chemistry Section',
            'rack_location' => 'COBAS-C501-SLOT-18',
            'notes' => 'Reagent calibration verified.'
        ],
        [
            'sample_id' => 'SMP-2026-00132',
            'request_id' => 'LAB-2026-009',
            'patient_name' => 'Maria Clara Santos',
            'patient_id' => 'P-2026-0002',
            'test' => 'Complete Blood Count (CBC)',
            'sample_type' => 'Whole Blood (EDTA)',
            'collection_date' => '2026-08-28',
            'collection_time' => '10:05 AM',
            'collected_by' => 'MedTech Robert Santos, RMT',
            'condition' => 'Acceptable',
            'status' => 'Completed',
            'stage_index' => 4,
            'section' => 'Hematology Section',
            'rack_location' => 'ARCHIVE-HEM-12',
            'notes' => 'Mild normocytic anemia noted. Released to attending OB.'
        ],
        [
            'sample_id' => 'SMP-2026-00135',
            'request_id' => 'LAB-2026-012',
            'patient_name' => 'Gabriel Mendoza',
            'patient_id' => 'P-2026-0010',
            'test' => 'COVID-19 & Respiratory Panel',
            'sample_type' => 'Nasopharyngeal Swab',
            'collection_date' => '2026-08-28',
            'collection_time' => '10:50 AM',
            'collected_by' => 'MedTech Ana Lim, RMT',
            'condition' => 'Acceptable (Cold chain intact)',
            'status' => 'Processing',
            'stage_index' => 2,
            'section' => 'Molecular Section',
            'rack_location' => 'BIO-CABINET-3-PCR',
            'notes' => 'Thermal cycling running - Cycle 24 of 40.'
        ],
        [
            'sample_id' => 'SMP-2026-00118',
            'request_id' => 'LAB-2026-023',
            'patient_name' => 'Angelica Mae Reyes',
            'patient_id' => 'P-2026-0004',
            'test' => 'Serum Potassium (K+)',
            'sample_type' => 'Serum (Red Top)',
            'collection_date' => '2026-08-28',
            'collection_time' => '07:30 AM',
            'collected_by' => 'Nurse Ward B',
            'condition' => 'Grossly Hemolyzed (Rejected)',
            'status' => 'Rejected',
            'stage_index' => 5, // Rejected
            'section' => 'Chemistry Section',
            'rack_location' => 'REJECT-BIN-01',
            'notes' => 'Sample grossly hemolyzed (index > 400). Recollection request issued.'
        ]
    ];
}

function getDemoLabResults(): array
{
    return [
        [
            'result_id' => 'RES-2026-001',
            'request_id' => 'LAB-2026-001',
            'sample_id' => 'SMP-2026-00124',
            'patient_id' => 'P-2026-0001',
            'patient_name' => 'Juan Dela Cruz',
            'age' => 45,
            'gender' => 'Male',
            'doctor' => 'Dr. Michael Reyes',
            'test' => 'Complete Blood Count (CBC)',
            'date' => '2026-08-28',
            'time' => '09:10 AM',
            'technologist' => 'Robert Santos, RMT (PRC: 0084920)',
            'pathologist' => 'Dr. Vicente Gomez, MD, FPSP (Pathologist)',
            'status' => 'For Verification',
            'summary' => 'Leukocytosis with Neutrophilia (Bacterial Infection Pattern)',
            'parameters' => [
                ['name' => 'Hemoglobin', 'value' => '14.2', 'unit' => 'g/dL', 'range' => '13.0 – 17.5', 'flag' => 'Normal'],
                ['name' => 'Hematocrit', 'value' => '42.5', 'unit' => '%', 'range' => '40.0 – 52.0', 'flag' => 'Normal'],
                ['name' => 'WBC Count', 'value' => '14.8', 'unit' => 'x10⁹/L', 'range' => '4.5 – 11.0', 'flag' => 'High'],
                ['name' => 'RBC Count', 'value' => '4.85', 'unit' => 'x10¹²/L', 'range' => '4.5 – 5.9', 'flag' => 'Normal'],
                ['name' => 'Platelet Count', 'value' => '245', 'unit' => 'x10⁹/L', 'range' => '150 – 450', 'flag' => 'Normal'],
                ['name' => 'Segmenters / Neutrophils', 'value' => '78', 'unit' => '%', 'range' => '50 – 70', 'flag' => 'High'],
                ['name' => 'Lymphocytes', 'value' => '16', 'unit' => '%', 'range' => '20 – 40', 'flag' => 'Low'],
                ['name' => 'Monocytes', 'value' => '4', 'unit' => '%', 'range' => '2 – 8', 'flag' => 'Normal'],
                ['name' => 'Eosinophils', 'value' => '2', 'unit' => '%', 'range' => '1 – 4', 'flag' => 'Normal'],
                ['name' => 'Basophils', 'value' => '0', 'unit' => '%', 'range' => '0 – 1', 'flag' => 'Normal']
            ],
            'interpretation' => 'Significant neutrophilic leukocytosis noted consistent with acute bacterial inflammatory reaction. Platelet and red cell indices are within normal physiological thresholds.'
        ],
        [
            'result_id' => 'RES-2026-002',
            'request_id' => 'LAB-2026-006',
            'sample_id' => 'SMP-2026-00129',
            'patient_id' => 'P-2026-0012',
            'patient_name' => 'Mark Anthony Ramos',
            'age' => 19,
            'gender' => 'Male',
            'doctor' => 'Dr. Gabriel Mercado',
            'test' => 'Dengue Duo Rapid Panel',
            'date' => '2026-08-28',
            'time' => '09:48 AM',
            'technologist' => 'Robert Santos, RMT (PRC: 0084920)',
            'pathologist' => 'Dr. Vicente Gomez, MD, FPSP (Pathologist)',
            'status' => 'Completed',
            'summary' => 'Dengue NS1 Antigen Reactive (Acute Infection Phase)',
            'parameters' => [
                ['name' => 'Dengue NS1 Antigen', 'value' => 'REACTIVE (+)', 'unit' => 'Qualitative', 'range' => 'Non-Reactive', 'flag' => 'Critical'],
                ['name' => 'Dengue IgM Antibody', 'value' => 'REACTIVE (+)', 'unit' => 'Qualitative', 'range' => 'Non-Reactive', 'flag' => 'High'],
                ['name' => 'Dengue IgG Antibody', 'value' => 'NON-REACTIVE (-)', 'unit' => 'Qualitative', 'range' => 'Non-Reactive', 'flag' => 'Normal']
            ],
            'interpretation' => 'Positive NS1 Antigen and IgM indicate acute Primary Dengue Viral Infection (Day 1-5). Close monitoring of hematocrit and platelet count is urgently advised.'
        ],
        [
            'result_id' => 'RES-2026-003',
            'request_id' => 'LAB-2026-005',
            'sample_id' => 'SMP-2026-00128',
            'patient_id' => 'P-2026-0007',
            'patient_name' => 'Kristine Joy Garcia',
            'age' => 29,
            'gender' => 'Female',
            'doctor' => 'Dr. Gabriel Mercado',
            'test' => 'Routine Urinalysis',
            'date' => '2026-08-28',
            'time' => '09:35 AM',
            'technologist' => 'Robert Santos, RMT (PRC: 0084920)',
            'pathologist' => 'Dr. Vicente Gomez, MD, FPSP (Pathologist)',
            'status' => 'Completed',
            'summary' => 'Pyuria and Bacteriuria noted (Acute Cystitis Pattern)',
            'parameters' => [
                ['name' => 'Color / Clarity', 'value' => 'Yellow / Turbid', 'unit' => 'Visual', 'range' => 'Straw-Yellow / Clear', 'flag' => 'Low'],
                ['name' => 'Specific Gravity', 'value' => '1.025', 'unit' => '—', 'range' => '1.010 – 1.030', 'flag' => 'Normal'],
                ['name' => 'pH', 'value' => '6.5', 'unit' => 'pH', 'range' => '5.0 – 7.5', 'flag' => 'Normal'],
                ['name' => 'Protein', 'value' => 'Trace', 'unit' => 'Dipstick', 'range' => 'Negative', 'flag' => 'Normal'],
                ['name' => 'Glucose', 'value' => 'Negative', 'unit' => 'Dipstick', 'range' => 'Negative', 'flag' => 'Normal'],
                ['name' => 'Leukocyte Esterase', 'value' => '3+ (Large)', 'unit' => 'Dipstick', 'range' => 'Negative', 'flag' => 'High'],
                ['name' => 'Nitrite', 'value' => 'Positive (+)', 'unit' => 'Dipstick', 'range' => 'Negative', 'flag' => 'High'],
                ['name' => 'Pus Cells (WBC)', 'value' => '25 - 35', 'unit' => '/hpf', 'range' => '0 – 5', 'flag' => 'High'],
                ['name' => 'RBC (Erythrocytes)', 'value' => '4 - 8', 'unit' => '/hpf', 'range' => '0 – 2', 'flag' => 'High'],
                ['name' => 'Bacteria', 'value' => 'Many (+++)', 'unit' => '/hpf', 'range' => 'Few / None', 'flag' => 'High']
            ],
            'interpretation' => 'Urinalysis shows significant pyuria, positive nitrites, and many bacteria consistent with Acute Lower Urinary Tract Infection (UTI).'
        ],
        [
            'result_id' => 'RES-2026-004',
            'request_id' => 'LAB-2026-007',
            'sample_id' => 'SMP-2026-00130',
            'patient_id' => 'P-2026-0006',
            'patient_name' => 'Crisanto Valenzuela',
            'age' => 41,
            'gender' => 'Male',
            'doctor' => 'Dr. Michael Reyes',
            'test' => 'Lipid Profile Panel',
            'date' => '2026-08-28',
            'time' => '10:05 AM',
            'technologist' => 'Robert Santos, RMT (PRC: 0084920)',
            'pathologist' => 'Dr. Vicente Gomez, MD, FPSP (Pathologist)',
            'status' => 'Completed',
            'summary' => 'Mixed Dyslipidemia with Elevated LDL & Triglycerides',
            'parameters' => [
                ['name' => 'Total Cholesterol', 'value' => '248', 'unit' => 'mg/dL', 'range' => '< 200', 'flag' => 'High'],
                ['name' => 'Triglycerides', 'value' => '210', 'unit' => 'mg/dL', 'range' => '< 150', 'flag' => 'High'],
                ['name' => 'HDL Cholesterol', 'value' => '36', 'unit' => 'mg/dL', 'range' => '> 40 (Male)', 'flag' => 'Low'],
                ['name' => 'LDL Cholesterol (Direct)', 'value' => '170', 'unit' => 'mg/dL', 'range' => '< 100', 'flag' => 'High'],
                ['name' => 'VLDL Cholesterol', 'value' => '42', 'unit' => 'mg/dL', 'range' => '< 30', 'flag' => 'High'],
                ['name' => 'Cholesterol / HDL Ratio', 'value' => '6.88', 'unit' => 'Ratio', 'range' => '< 4.5', 'flag' => 'High']
            ],
            'interpretation' => 'High atherogenic lipid profile. Dietary lipid modification and therapeutic statin review recommended.'
        ],
        [
            'result_id' => 'RES-2026-005',
            'request_id' => 'LAB-2026-009',
            'sample_id' => 'SMP-2026-00132',
            'patient_id' => 'P-2026-0002',
            'patient_name' => 'Maria Clara Santos',
            'age' => 32,
            'gender' => 'Female',
            'doctor' => 'Dr. Elena Villanueva',
            'test' => 'Complete Blood Count (CBC)',
            'date' => '2026-08-28',
            'time' => '10:30 AM',
            'technologist' => 'Robert Santos, RMT (PRC: 0084920)',
            'pathologist' => 'Dr. Vicente Gomez, MD, FPSP (Pathologist)',
            'status' => 'Completed',
            'summary' => 'Mild Gestational Anemia (Hb 10.8 g/dL)',
            'parameters' => [
                ['name' => 'Hemoglobin', 'value' => '10.8', 'unit' => 'g/dL', 'range' => '12.0 – 15.5', 'flag' => 'Low'],
                ['name' => 'Hematocrit', 'value' => '33.2', 'unit' => '%', 'range' => '36.0 – 48.0', 'flag' => 'Low'],
                ['name' => 'WBC Count', 'value' => '8.6', 'unit' => 'x10⁹/L', 'range' => '4.5 – 11.0', 'flag' => 'Normal'],
                ['name' => 'RBC Count', 'value' => '3.80', 'unit' => 'x10¹²/L', 'range' => '4.0 – 5.2', 'flag' => 'Low'],
                ['name' => 'Platelet Count', 'value' => '280', 'unit' => 'x10⁹/L', 'range' => '150 – 450', 'flag' => 'Normal']
            ],
            'interpretation' => 'Mild normocytic normochromic anemia consistent with physiologic hemodilution of pregnancy / mild iron deficiency.'
        ]
    ];
}

function getDemoRecentActivity(): array
{
    return [
        ['type' => 'result', 'title' => 'CBC Result Recorded & Flagged', 'detail' => 'Patient Juan Dela Cruz (LAB-2026-001) - Leukocytosis flagged', 'time' => '2 minutes ago', 'icon' => 'file-check'],
        ['type' => 'sample', 'title' => 'Sample Loaded in Analyzer', 'detail' => 'Sample SMP-2026-00127 (Eduardo Dizon) running in Cobas c501', 'time' => '8 minutes ago', 'icon' => 'flask-conical'],
        ['type' => 'request', 'title' => 'STAT Laboratory Request Accepted', 'detail' => 'Dr. Antonio Mendoza requested STAT Electrolytes for Rodrigo Morales', 'time' => '15 minutes ago', 'icon' => 'clipboard-check'],
        ['type' => 'report', 'title' => 'Diagnostic Report Generated & Printed', 'detail' => 'Dengue Duo Panel for Mark Anthony Ramos released to ER', 'time' => '24 minutes ago', 'icon' => 'printer'],
        ['type' => 'sample', 'title' => 'Sample Rejection & Recollection Logged', 'detail' => 'Sample SMP-2026-00118 rejected due to gross hemolysis', 'time' => '42 minutes ago', 'icon' => 'alert-triangle']
    ];
}

function getDemoNotifications(): array
{
    return [
        [
            'id' => 'NOTIF-01',
            'title' => 'New STAT Laboratory Request',
            'message' => 'Patient Rodrigo Morales (ICU Bed 03) requires urgent STAT Serum Electrolytes processing.',
            'time' => '5 mins ago',
            'type' => 'critical',
            'unread' => true,
            'action_link' => 'requests'
        ],
        [
            'id' => 'NOTIF-02',
            'title' => 'Sample Rejected — Recollection Alert',
            'message' => 'Sample SMP-2026-00118 was grossly hemolyzed. Ward Nurse notified for immediate redraw.',
            'time' => '30 mins ago',
            'type' => 'warning',
            'unread' => true,
            'action_link' => 'samples'
        ],
        [
            'id' => 'NOTIF-03',
            'title' => 'Result Ready For Pathologist Verification',
            'message' => 'CBC for Juan Dela Cruz (LAB-2026-001) with elevated WBC (14.8) awaits final digital sign-off.',
            'time' => '45 mins ago',
            'type' => 'info',
            'unread' => false,
            'action_link' => 'results'
        ],
        [
            'id' => 'NOTIF-04',
            'title' => 'New Laboratory Request Received',
            'message' => 'Dr. Rafael Cruz submitted a pre-op ABO Typing request for Teresa May Aquino.',
            'time' => '1 hour ago',
            'type' => 'info',
            'unread' => false,
            'action_link' => 'requests'
        ]
    ];
}
