<?php
// Nurse/includes/demo_data.php

/**
 * Demo patient data for Nurse On Duty Portal
 * 15 patients with realistic Philippine-style names
 */
function getDemoPatients(): array
{
    return [
        [
            'id' => 'P-2026-0001',
            'name' => 'Juan Dela Cruz',
            'age' => 45,
            'gender' => 'Male',
            'contact' => '+63 917 123 4567',
            'room' => 'Room 204',
            'attending_physician' => 'Dr. Michael Reyes',
            'status' => 'Under Observation',
            'bp' => '120/80',
            'heart_rate' => 78,
            'temperature' => 36.7,
            'respiratory_rate' => 18,
            'spo2' => 98,
            'pain_level' => 2,
            'queue_status' => 'Under Observation',
            'queue_number' => 2,
            'assigned_task' => 'Check vital signs',
            'task_status' => 'Pending',
            'task_priority' => 'High',
            'task_due' => '10:30 AM',
            'last_update' => '2 minutes ago',
            'medical_history' => 'Hypertension Stage 1, Type 2 Diabetes Mellitus',
            'allergies' => 'Penicillin',
            'admission_date' => '2026-08-26',
        ],
        [
            'id' => 'P-2026-0002',
            'name' => 'Maria Lopez',
            'age' => 32,
            'gender' => 'Female',
            'contact' => '+63 918 234 5678',
            'room' => 'Room 102',
            'attending_physician' => 'Dr. Elena Villanueva',
            'status' => 'Stable',
            'bp' => '110/70',
            'heart_rate' => 72,
            'temperature' => 36.5,
            'respiratory_rate' => 16,
            'spo2' => 99,
            'pain_level' => 0,
            'queue_status' => 'Waiting',
            'queue_number' => 1,
            'assigned_task' => 'Assist patient transfer',
            'task_status' => 'In Progress',
            'task_priority' => 'Medium',
            'task_due' => '11:00 AM',
            'last_update' => '8 minutes ago',
            'medical_history' => 'Asthma (mild intermittent)',
            'allergies' => 'None',
            'admission_date' => '2026-08-27',
        ],
        [
            'id' => 'P-2026-0003',
            'name' => 'Ana Garcia',
            'age' => 58,
            'gender' => 'Female',
            'contact' => '+63 919 345 6789',
            'room' => 'Room 305',
            'attending_physician' => 'Dr. Roberto Santos',
            'status' => 'Stable',
            'bp' => '130/85',
            'heart_rate' => 80,
            'temperature' => 36.8,
            'respiratory_rate' => 17,
            'spo2' => 97,
            'pain_level' => 3,
            'queue_status' => 'Ready for Consultation',
            'queue_number' => 3,
            'assigned_task' => 'Administer medication',
            'task_status' => 'Pending',
            'task_priority' => 'High',
            'task_due' => '11:30 AM',
            'last_update' => '15 minutes ago',
            'medical_history' => 'Osteoarthritis, GERD',
            'allergies' => 'Sulfa drugs',
            'admission_date' => '2026-08-25',
        ],
        [
            'id' => 'P-2026-0004',
            'name' => 'Ricardo Bautista',
            'age' => 67,
            'gender' => 'Male',
            'contact' => '+63 920 456 7890',
            'room' => 'Room 401',
            'attending_physician' => 'Dr. Michael Reyes',
            'status' => 'Critical',
            'bp' => '160/100',
            'heart_rate' => 102,
            'temperature' => 38.2,
            'respiratory_rate' => 24,
            'spo2' => 92,
            'pain_level' => 7,
            'queue_status' => 'In Progress',
            'queue_number' => 4,
            'assigned_task' => 'Monitor BP every 30 minutes',
            'task_status' => 'In Progress',
            'task_priority' => 'High',
            'task_due' => '09:00 AM',
            'last_update' => '1 minute ago',
            'medical_history' => 'Congestive Heart Failure, Atrial Fibrillation, CKD Stage 3',
            'allergies' => 'ACE Inhibitors',
            'admission_date' => '2026-08-24',
        ],
        [
            'id' => 'P-2026-0005',
            'name' => 'Lourdes Fernandez',
            'age' => 41,
            'gender' => 'Female',
            'contact' => '+63 921 567 8901',
            'room' => 'Room 108',
            'attending_physician' => 'Dr. Elena Villanueva',
            'status' => 'For Discharge',
            'bp' => '118/76',
            'heart_rate' => 70,
            'temperature' => 36.4,
            'respiratory_rate' => 15,
            'spo2' => 99,
            'pain_level' => 1,
            'queue_status' => 'Completed',
            'queue_number' => 5,
            'assigned_task' => 'Prepare discharge papers',
            'task_status' => 'Pending',
            'task_priority' => 'Medium',
            'task_due' => '12:00 PM',
            'last_update' => '30 minutes ago',
            'medical_history' => 'Appendectomy (2024)',
            'allergies' => 'None',
            'admission_date' => '2026-08-26',
        ],
        [
            'id' => 'P-2026-0006',
            'name' => 'Carlos Mendoza',
            'age' => 55,
            'gender' => 'Male',
            'contact' => '+63 922 678 9012',
            'room' => 'Room 210',
            'attending_physician' => 'Dr. Roberto Santos',
            'status' => 'Needs Attention',
            'bp' => '145/92',
            'heart_rate' => 88,
            'temperature' => 37.6,
            'respiratory_rate' => 20,
            'spo2' => 95,
            'pain_level' => 5,
            'queue_status' => 'Waiting',
            'queue_number' => 6,
            'assigned_task' => 'Check wound dressing',
            'task_status' => 'Pending',
            'task_priority' => 'High',
            'task_due' => '10:00 AM',
            'last_update' => '5 minutes ago',
            'medical_history' => 'Post-op cholecystectomy, Hypertension',
            'allergies' => 'Ibuprofen',
            'admission_date' => '2026-08-27',
        ],
        [
            'id' => 'P-2026-0007',
            'name' => 'Rosa Aquino',
            'age' => 72,
            'gender' => 'Female',
            'contact' => '+63 923 789 0123',
            'room' => 'Room 312',
            'attending_physician' => 'Dr. Michael Reyes',
            'status' => 'Under Observation',
            'bp' => '138/88',
            'heart_rate' => 76,
            'temperature' => 36.9,
            'respiratory_rate' => 19,
            'spo2' => 96,
            'pain_level' => 4,
            'queue_status' => 'Called',
            'queue_number' => 7,
            'assigned_task' => 'Assist with ambulation',
            'task_status' => 'Completed',
            'task_priority' => 'Low',
            'task_due' => '09:30 AM',
            'last_update' => '20 minutes ago',
            'medical_history' => 'Osteoporosis, Hypothyroidism',
            'allergies' => 'Codeine',
            'admission_date' => '2026-08-23',
        ],
        [
            'id' => 'P-2026-0008',
            'name' => 'Eduardo Ramos',
            'age' => 38,
            'gender' => 'Male',
            'contact' => '+63 924 890 1234',
            'room' => 'Room 115',
            'attending_physician' => 'Dr. Elena Villanueva',
            'status' => 'Stable',
            'bp' => '122/78',
            'heart_rate' => 68,
            'temperature' => 36.6,
            'respiratory_rate' => 16,
            'spo2' => 98,
            'pain_level' => 1,
            'queue_status' => 'Waiting',
            'queue_number' => 8,
            'assigned_task' => 'Record intake/output',
            'task_status' => 'In Progress',
            'task_priority' => 'Medium',
            'task_due' => '12:00 PM',
            'last_update' => '25 minutes ago',
            'medical_history' => 'Pneumonia (resolving)',
            'allergies' => 'None',
            'admission_date' => '2026-08-26',
        ],
        [
            'id' => 'P-2026-0009',
            'name' => 'Felicidad Torres',
            'age' => 63,
            'gender' => 'Female',
            'contact' => '+63 925 901 2345',
            'room' => 'Room 220',
            'attending_physician' => 'Dr. Roberto Santos',
            'status' => 'Stable',
            'bp' => '125/82',
            'heart_rate' => 74,
            'temperature' => 36.5,
            'respiratory_rate' => 17,
            'spo2' => 97,
            'pain_level' => 2,
            'queue_status' => 'Completed',
            'queue_number' => 9,
            'assigned_task' => 'Post-op monitoring',
            'task_status' => 'Completed',
            'task_priority' => 'Medium',
            'task_due' => '08:00 AM',
            'last_update' => '45 minutes ago',
            'medical_history' => 'Total knee replacement (right)',
            'allergies' => 'Latex',
            'admission_date' => '2026-08-25',
        ],
        [
            'id' => 'P-2026-0010',
            'name' => 'Antonio Villanueva',
            'age' => 50,
            'gender' => 'Male',
            'contact' => '+63 926 012 3456',
            'room' => 'Room 303',
            'attending_physician' => 'Dr. Michael Reyes',
            'status' => 'Under Observation',
            'bp' => '132/86',
            'heart_rate' => 82,
            'temperature' => 37.1,
            'respiratory_rate' => 18,
            'spo2' => 96,
            'pain_level' => 3,
            'queue_status' => 'Waiting',
            'queue_number' => 10,
            'assigned_task' => 'ECG monitoring',
            'task_status' => 'Pending',
            'task_priority' => 'High',
            'task_due' => '01:00 PM',
            'last_update' => '10 minutes ago',
            'medical_history' => 'Unstable Angina, Dyslipidemia',
            'allergies' => 'Aspirin',
            'admission_date' => '2026-08-27',
        ],
        [
            'id' => 'P-2026-0011',
            'name' => 'Consolacion Pascual',
            'age' => 78,
            'gender' => 'Female',
            'contact' => '+63 927 123 4567',
            'room' => 'Room 408',
            'attending_physician' => 'Dr. Elena Villanueva',
            'status' => 'Needs Attention',
            'bp' => '150/95',
            'heart_rate' => 94,
            'temperature' => 37.8,
            'respiratory_rate' => 22,
            'spo2' => 93,
            'pain_level' => 6,
            'queue_status' => 'Called',
            'queue_number' => 11,
            'assigned_task' => 'Oxygen therapy monitoring',
            'task_status' => 'In Progress',
            'task_priority' => 'High',
            'task_due' => '09:45 AM',
            'last_update' => '3 minutes ago',
            'medical_history' => 'COPD, Diabetes Mellitus Type 2, Hypertension',
            'allergies' => 'Metformin',
            'admission_date' => '2026-08-24',
        ],
        [
            'id' => 'P-2026-0012',
            'name' => 'Miguel Santos Jr.',
            'age' => 28,
            'gender' => 'Male',
            'contact' => '+63 928 234 5678',
            'room' => 'Room 105',
            'attending_physician' => 'Dr. Roberto Santos',
            'status' => 'Stable',
            'bp' => '115/72',
            'heart_rate' => 66,
            'temperature' => 36.4,
            'respiratory_rate' => 15,
            'spo2' => 99,
            'pain_level' => 1,
            'queue_status' => 'Waiting',
            'queue_number' => 12,
            'assigned_task' => 'IV fluid monitoring',
            'task_status' => 'In Progress',
            'task_priority' => 'Low',
            'task_due' => '02:00 PM',
            'last_update' => '35 minutes ago',
            'medical_history' => 'Dengue Fever (recovering)',
            'allergies' => 'None',
            'admission_date' => '2026-08-26',
        ],
        [
            'id' => 'P-2026-0013',
            'name' => 'Remedios Abella',
            'age' => 60,
            'gender' => 'Female',
            'contact' => '+63 929 345 6789',
            'room' => 'Room 215',
            'attending_physician' => 'Dr. Michael Reyes',
            'status' => 'Stable',
            'bp' => '128/80',
            'heart_rate' => 75,
            'temperature' => 36.6,
            'respiratory_rate' => 16,
            'spo2' => 97,
            'pain_level' => 2,
            'queue_status' => 'Completed',
            'queue_number' => 13,
            'assigned_task' => 'Medication administration',
            'task_status' => 'Completed',
            'task_priority' => 'Medium',
            'task_due' => '08:30 AM',
            'last_update' => '1 hour ago',
            'medical_history' => 'Chronic Kidney Disease Stage 2, Anemia',
            'allergies' => 'Erythromycin',
            'admission_date' => '2026-08-25',
        ],
        [
            'id' => 'P-2026-0014',
            'name' => 'Gabriel Cruz',
            'age' => 34,
            'gender' => 'Male',
            'contact' => '+63 930 456 7890',
            'room' => 'Room 118',
            'attending_physician' => 'Dr. Elena Villanueva',
            'status' => 'For Discharge',
            'bp' => '116/74',
            'heart_rate' => 70,
            'temperature' => 36.5,
            'respiratory_rate' => 16,
            'spo2' => 99,
            'pain_level' => 0,
            'queue_status' => 'Completed',
            'queue_number' => 14,
            'assigned_task' => 'Final vital signs check',
            'task_status' => 'Pending',
            'task_priority' => 'Medium',
            'task_due' => '01:30 PM',
            'last_update' => '40 minutes ago',
            'medical_history' => 'Fractured right radius (healed)',
            'allergies' => 'None',
            'admission_date' => '2026-08-23',
        ],
        [
            'id' => 'P-2026-0015',
            'name' => 'Esperanza Dimaculangan',
            'age' => 52,
            'gender' => 'Female',
            'contact' => '+63 931 567 8901',
            'room' => 'Room 310',
            'attending_physician' => 'Dr. Roberto Santos',
            'status' => 'Under Observation',
            'bp' => '135/88',
            'heart_rate' => 84,
            'temperature' => 37.3,
            'respiratory_rate' => 19,
            'spo2' => 96,
            'pain_level' => 4,
            'queue_status' => 'In Progress',
            'queue_number' => 15,
            'assigned_task' => 'Blood sugar monitoring',
            'task_status' => 'Pending',
            'task_priority' => 'High',
            'task_due' => '11:45 AM',
            'last_update' => '7 minutes ago',
            'medical_history' => 'Diabetes Mellitus Type 2, Diabetic Neuropathy',
            'allergies' => 'Glipizide',
            'admission_date' => '2026-08-27',
        ],
    ];
}

/**
 * Demo doctor instructions
 */
function getDemoInstructions(): array
{
    return [
        [
            'doctor' => 'Dr. Michael Reyes',
            'patient' => 'Juan Dela Cruz',
            'room' => 'Room 204',
            'instruction' => 'Monitor blood pressure every 4 hours and report significant changes. Administer Amlodipine 5mg daily.',
            'priority' => 'High',
            'status' => 'Active',
            'date' => '2026-08-28 08:00:00',
        ],
        [
            'doctor' => 'Dr. Michael Reyes',
            'patient' => 'Ricardo Bautista',
            'room' => 'Room 401',
            'instruction' => 'Strict fluid intake/output monitoring. IV Furosemide 40mg every 12 hours. Elevate HOB to 45 degrees. Continuous cardiac monitoring.',
            'priority' => 'High',
            'status' => 'Active',
            'date' => '2026-08-28 07:30:00',
        ],
        [
            'doctor' => 'Dr. Elena Villanueva',
            'patient' => 'Maria Lopez',
            'room' => 'Room 102',
            'instruction' => 'Nebulize with Salbutamol PRN for wheezing. Observe for respiratory distress. May ambulate as tolerated.',
            'priority' => 'Medium',
            'status' => 'Active',
            'date' => '2026-08-28 09:00:00',
        ],
        [
            'doctor' => 'Dr. Roberto Santos',
            'patient' => 'Ana Garcia',
            'room' => 'Room 305',
            'instruction' => 'Continue physical therapy exercises. Paracetamol 500mg for pain PRN. Schedule follow-up X-ray.',
            'priority' => 'Medium',
            'status' => 'Active',
            'date' => '2026-08-28 08:45:00',
        ],
        [
            'doctor' => 'Dr. Elena Villanueva',
            'patient' => 'Consolacion Pascual',
            'room' => 'Room 408',
            'instruction' => 'Maintain O2 at 2L/min via nasal cannula. Monitor SpO2 hourly. If SpO2 drops below 92%, notify physician immediately.',
            'priority' => 'High',
            'status' => 'Active',
            'date' => '2026-08-28 07:00:00',
        ],
    ];
}

/**
 * Demo notifications
 */
function getDemoNotifications(): array
{
    return [
        [
            'type' => 'instruction',
            'title' => 'New Doctor Instruction',
            'message' => 'Dr. Reyes added instructions for Room 204.',
            'time' => '2 minutes ago',
            'read' => false,
            'icon' => 'file-text',
            'color' => 'blue',
        ],
        [
            'type' => 'status',
            'title' => 'Patient Status Changed',
            'message' => 'Juan Dela Cruz changed to "Needs Attention."',
            'time' => '5 minutes ago',
            'read' => false,
            'icon' => 'alert-triangle',
            'color' => 'amber',
        ],
        [
            'type' => 'task',
            'title' => 'New Assigned Task',
            'message' => 'You have been assigned a new patient monitoring task.',
            'time' => '12 minutes ago',
            'read' => false,
            'icon' => 'clipboard-check',
            'color' => 'teal',
        ],
        [
            'type' => 'queue',
            'title' => 'Queue Update',
            'message' => 'Patient queue has been updated.',
            'time' => '18 minutes ago',
            'read' => false,
            'icon' => 'list-ordered',
            'color' => 'purple',
        ],
        [
            'type' => 'instruction',
            'title' => 'Instruction Update',
            'message' => 'Dr. Villanueva updated oxygen therapy instructions for Room 408.',
            'time' => '25 minutes ago',
            'read' => true,
            'icon' => 'file-text',
            'color' => 'blue',
        ],
        [
            'type' => 'status',
            'title' => 'Patient Discharge Approved',
            'message' => 'Lourdes Fernandez approved for discharge by Dr. Villanueva.',
            'time' => '40 minutes ago',
            'read' => true,
            'icon' => 'check-circle',
            'color' => 'emerald',
        ],
        [
            'type' => 'task',
            'title' => 'Task Completed',
            'message' => 'Post-op monitoring for Felicidad Torres marked as completed.',
            'time' => '1 hour ago',
            'read' => true,
            'icon' => 'check-circle',
            'color' => 'emerald',
        ],
    ];
}

/**
 * Demo vital signs history
 */
function getDemoVitalHistory(string $patientId = 'P-2026-0001'): array
{
    return [
        ['date' => 'Aug 28, 2026', 'time' => '10:00 AM', 'bp' => '120/80', 'hr' => 78, 'temp' => 36.7, 'rr' => 18, 'spo2' => 98, 'pain' => 2, 'recorded_by' => 'Nurse Maria Santos'],
        ['date' => 'Aug 28, 2026', 'time' => '06:00 AM', 'bp' => '122/82', 'hr' => 80, 'temp' => 36.8, 'rr' => 17, 'spo2' => 97, 'pain' => 3, 'recorded_by' => 'Nurse Patricia Lim'],
        ['date' => 'Aug 27, 2026', 'time' => '10:00 PM', 'bp' => '125/84', 'hr' => 76, 'temp' => 36.6, 'rr' => 16, 'spo2' => 98, 'pain' => 2, 'recorded_by' => 'Nurse Angela Reyes'],
        ['date' => 'Aug 27, 2026', 'time' => '06:00 PM', 'bp' => '128/86', 'hr' => 82, 'temp' => 37.0, 'rr' => 19, 'spo2' => 97, 'pain' => 4, 'recorded_by' => 'Nurse Maria Santos'],
        ['date' => 'Aug 27, 2026', 'time' => '02:00 PM', 'bp' => '130/88', 'hr' => 84, 'temp' => 37.2, 'rr' => 20, 'spo2' => 96, 'pain' => 5, 'recorded_by' => 'Nurse Patricia Lim'],
        ['date' => 'Aug 27, 2026', 'time' => '10:00 AM', 'bp' => '132/88', 'hr' => 86, 'temp' => 37.1, 'rr' => 19, 'spo2' => 96, 'pain' => 4, 'recorded_by' => 'Nurse Maria Santos'],
        ['date' => 'Aug 27, 2026', 'time' => '06:00 AM', 'bp' => '135/90', 'hr' => 88, 'temp' => 37.4, 'rr' => 21, 'spo2' => 95, 'pain' => 5, 'recorded_by' => 'Nurse Angela Reyes'],
        ['date' => 'Aug 26, 2026', 'time' => '10:00 PM', 'bp' => '140/92', 'hr' => 90, 'temp' => 37.6, 'rr' => 22, 'spo2' => 94, 'pain' => 6, 'recorded_by' => 'Nurse Patricia Lim'],
    ];
}

/**
 * Get vital sign status based on value
 */
function getVitalStatus(string $type, $value): string
{
    switch ($type) {
        case 'heart_rate':
            if ($value < 60 || $value > 100) return $value < 50 || $value > 120 ? 'Critical' : 'Warning';
            return 'Normal';
        case 'temperature':
            if ($value > 38.0 || $value < 36.0) return $value > 39.0 || $value < 35.0 ? 'Critical' : 'Warning';
            return 'Normal';
        case 'spo2':
            if ($value < 95) return $value < 90 ? 'Critical' : 'Warning';
            return 'Normal';
        case 'respiratory_rate':
            if ($value < 12 || $value > 20) return $value < 8 || $value > 28 ? 'Critical' : 'Warning';
            return 'Normal';
        case 'pain_level':
            if ($value >= 7) return 'Critical';
            if ($value >= 4) return 'Warning';
            return 'Normal';
        case 'bp_systolic':
            if ($value > 140 || $value < 90) return $value > 180 || $value < 70 ? 'Critical' : 'Warning';
            return 'Normal';
        default:
            return 'Normal';
    }
}
