<?php
// Pharmacy/includes/demo_data.php
// Demo Data Provider for Pharmacy Portal – Tupi Municipal Hospital Information Management System

// ============================================================
// PATIENTS (30 entries)
// ============================================================
function getDemoPatients(): array
{
    return [
        ['id'=>'P-2026-0001','name'=>'Juan Dela Cruz','age'=>45,'gender'=>'Male','blood_type'=>'O+','allergies'=>'Penicillin','contact'=>'+63 917 123 4567','room'=>'Room 204'],
        ['id'=>'P-2026-0002','name'=>'Maria Clara Santos','age'=>32,'gender'=>'Female','blood_type'=>'A+','allergies'=>'None Known','contact'=>'+63 918 234 5678','room'=>'Room 102'],
        ['id'=>'P-2026-0003','name'=>'Rodrigo Morales','age'=>58,'gender'=>'Male','blood_type'=>'B+','allergies'=>'Sulfonamides','contact'=>'+63 919 345 6789','room'=>'ICU Bed 03'],
        ['id'=>'P-2026-0004','name'=>'Angelica Mae Reyes','age'=>24,'gender'=>'Female','blood_type'=>'AB+','allergies'=>'None Known','contact'=>'+63 920 456 7890','room'=>'OPD Clinic 3'],
        ['id'=>'P-2026-0005','name'=>'Eduardo Dizon','age'=>67,'gender'=>'Male','blood_type'=>'O-','allergies'=>'NSAIDs','contact'=>'+63 921 567 8901','room'=>'Room 312'],
        ['id'=>'P-2026-0006','name'=>'Crisanto Valenzuela','age'=>41,'gender'=>'Male','blood_type'=>'A-','allergies'=>'None Known','contact'=>'+63 922 678 9012','room'=>'Room 208'],
        ['id'=>'P-2026-0007','name'=>'Kristine Joy Garcia','age'=>29,'gender'=>'Female','blood_type'=>'O+','allergies'=>'Aspirin','contact'=>'+63 923 789 0123','room'=>'ER Bed 06'],
        ['id'=>'P-2026-0008','name'=>'Leandro Bautista','age'=>52,'gender'=>'Male','blood_type'=>'B-','allergies'=>'None Known','contact'=>'+63 924 890 1234','room'=>'Room 405'],
        ['id'=>'P-2026-0009','name'=>'Teresa May Aquino','age'=>38,'gender'=>'Female','blood_type'=>'A+','allergies'=>'Codeine','contact'=>'+63 925 901 2345','room'=>'Room 110'],
        ['id'=>'P-2026-0010','name'=>'Gabriel Mendoza','age'=>63,'gender'=>'Male','blood_type'=>'AB-','allergies'=>'None Known','contact'=>'+63 926 012 3456','room'=>'Room 304'],
        ['id'=>'P-2026-0011','name'=>'Rosanna Cortez','age'=>49,'gender'=>'Female','blood_type'=>'O+','allergies'=>'None Known','contact'=>'+63 927 123 4567','room'=>'OPD Clinic 1'],
        ['id'=>'P-2026-0012','name'=>'Mark Anthony Ramos','age'=>19,'gender'=>'Male','blood_type'=>'B+','allergies'=>'None Known','contact'=>'+63 928 234 5678','room'=>'Room 115'],
        ['id'=>'P-2026-0013','name'=>'Florencia Magpayo','age'=>72,'gender'=>'Female','blood_type'=>'O+','allergies'=>'Tetracycline','contact'=>'+63 929 345 6789','room'=>'Room 306'],
        ['id'=>'P-2026-0014','name'=>'Danilo Ocampo','age'=>55,'gender'=>'Male','blood_type'=>'A+','allergies'=>'None Known','contact'=>'+63 930 456 7890','room'=>'Room 201'],
        ['id'=>'P-2026-0015','name'=>'Shirley Mae Dela Rosa','age'=>33,'gender'=>'Female','blood_type'=>'B+','allergies'=>'Ibuprofen','contact'=>'+63 931 567 8901','room'=>'OPD Clinic 5'],
        ['id'=>'P-2026-0016','name'=>'Ernesto Castillo','age'=>61,'gender'=>'Male','blood_type'=>'O-','allergies'=>'None Known','contact'=>'+63 932 678 9012','room'=>'Room 401'],
        ['id'=>'P-2026-0017','name'=>'Lourdes Panganiban','age'=>44,'gender'=>'Female','blood_type'=>'A+','allergies'=>'Erythromycin','contact'=>'+63 933 789 0123','room'=>'Room 203'],
        ['id'=>'P-2026-0018','name'=>'Renato Villanueva','age'=>37,'gender'=>'Male','blood_type'=>'AB+','allergies'=>'None Known','contact'=>'+63 934 890 1234','room'=>'ER Bed 02'],
        ['id'=>'P-2026-0019','name'=>'Corazon Enriquez','age'=>56,'gender'=>'Female','blood_type'=>'O+','allergies'=>'None Known','contact'=>'+63 935 901 2345','room'=>'Room 308'],
        ['id'=>'P-2026-0020','name'=>'Benedicto Soria','age'=>48,'gender'=>'Male','blood_type'=>'B-','allergies'=>'Morphine','contact'=>'+63 936 012 3456','room'=>'ICU Bed 01'],
        ['id'=>'P-2026-0021','name'=>'Maricel Tolentino','age'=>27,'gender'=>'Female','blood_type'=>'A-','allergies'=>'None Known','contact'=>'+63 937 123 4567','room'=>'OPD Clinic 2'],
        ['id'=>'P-2026-0022','name'=>'Alfredo Navarro','age'=>70,'gender'=>'Male','blood_type'=>'O+','allergies'=>'None Known','contact'=>'+63 938 234 5678','room'=>'Room 410'],
        ['id'=>'P-2026-0023','name'=>'Josephine Arceo','age'=>42,'gender'=>'Female','blood_type'=>'A+','allergies'=>'Amoxicillin','contact'=>'+63 939 345 6789','room'=>'Room 207'],
        ['id'=>'P-2026-0024','name'=>'Christopher Evangelista','age'=>31,'gender'=>'Male','blood_type'=>'B+','allergies'=>'None Known','contact'=>'+63 940 456 7890','room'=>'Room 105'],
        ['id'=>'P-2026-0025','name'=>'Remedios Cabrera','age'=>64,'gender'=>'Female','blood_type'=>'AB+','allergies'=>'Aspirin','contact'=>'+63 941 567 8901','room'=>'Room 313'],
        ['id'=>'P-2026-0026','name'=>'Nestor Abaya','age'=>53,'gender'=>'Male','blood_type'=>'O+','allergies'=>'None Known','contact'=>'+63 942 678 9012','room'=>'Room 217'],
        ['id'=>'P-2026-0027','name'=>'Glenda Lacson','age'=>36,'gender'=>'Female','blood_type'=>'A+','allergies'=>'None Known','contact'=>'+63 943 789 0123','room'=>'OPD Clinic 4'],
        ['id'=>'P-2026-0028','name'=>'Victorino Samonte','age'=>59,'gender'=>'Male','blood_type'=>'B+','allergies'=>'NSAIDs','contact'=>'+63 944 890 1234','room'=>'Room 403'],
        ['id'=>'P-2026-0029','name'=>'Carmelita Buendia','age'=>46,'gender'=>'Female','blood_type'=>'O-','allergies'=>'None Known','contact'=>'+63 945 901 2345','room'=>'Room 218'],
        ['id'=>'P-2026-0030','name'=>'Filemon Ibañez','age'=>68,'gender'=>'Male','blood_type'=>'A-','allergies'=>'Penicillin','contact'=>'+63 946 012 3456','room'=>'Room 315'],
    ];
}

// ============================================================
// PRESCRIPTIONS (30 entries)
// ============================================================
function getdemoPrescriptions(): array
{
    return [
        ['rx_id'=>'RX-2026-001','patient_name'=>'Juan Dela Cruz','patient_id'=>'P-2026-0001','age'=>45,'gender'=>'Male','allergies'=>'Penicillin','doctor'=>'Dr. Michael Reyes, MD','specialty'=>'Internal Medicine','rx_date'=>'2026-08-28','medicine'=>'Amoxicillin 500mg','generic'=>'Amoxicillin','dosage'=>'500mg','frequency'=>'3 times daily','route'=>'Oral','duration'=>'7 days','quantity'=>'21 capsules','instructions'=>'Take after meals. Avoid alcohol.','priority'=>'Routine','status'=>'Pending','drug_interaction'=>'None detected'],
        ['rx_id'=>'RX-2026-002','patient_name'=>'Maria Clara Santos','patient_id'=>'P-2026-0002','age'=>32,'gender'=>'Female','allergies'=>'None Known','doctor'=>'Dr. Elena Villanueva, MD','specialty'=>'Obstetrics','rx_date'=>'2026-08-28','medicine'=>'Ferrous Sulfate 325mg','generic'=>'Ferrous Sulfate','dosage'=>'325mg','frequency'=>'Once daily','route'=>'Oral','duration'=>'30 days','quantity'=>'30 tablets','instructions'=>'Take with orange juice. Avoid dairy.','priority'=>'Routine','status'=>'Verified','drug_interaction'=>'None detected'],
        ['rx_id'=>'RX-2026-003','patient_name'=>'Rodrigo Morales','patient_id'=>'P-2026-0003','age'=>58,'gender'=>'Male','allergies'=>'Sulfonamides','doctor'=>'Dr. Antonio Mendoza, MD','specialty'=>'Cardiology','rx_date'=>'2026-08-28','medicine'=>'Clopidogrel 75mg','generic'=>'Clopidogrel','dosage'=>'75mg','frequency'=>'Once daily','route'=>'Oral','duration'=>'30 days','quantity'=>'30 tablets','instructions'=>'Take at the same time daily. Monitor for bleeding.','priority'=>'STAT','status'=>'Ready for Dispensing','drug_interaction'=>'Aspirin – monitor closely'],
        ['rx_id'=>'RX-2026-004','patient_name'=>'Angelica Mae Reyes','patient_id'=>'P-2026-0004','age'=>24,'gender'=>'Female','allergies'=>'None Known','doctor'=>'Dr. Sophia Ramos, MD','specialty'=>'Endocrinology','rx_date'=>'2026-08-27','medicine'=>'Levothyroxine 50mcg','generic'=>'Levothyroxine','dosage'=>'50mcg','frequency'=>'Once daily','route'=>'Oral','duration'=>'30 days','quantity'=>'30 tablets','instructions'=>'Take 30 minutes before breakfast.','priority'=>'Routine','status'=>'Dispensed','drug_interaction'=>'None detected'],
        ['rx_id'=>'RX-2026-005','patient_name'=>'Eduardo Dizon','patient_id'=>'P-2026-0005','age'=>67,'gender'=>'Male','allergies'=>'NSAIDs','doctor'=>'Dr. Carlos Tan, MD','specialty'=>'Nephrology','rx_date'=>'2026-08-28','medicine'=>'Amlodipine 5mg','generic'=>'Amlodipine','dosage'=>'5mg','frequency'=>'Once daily','route'=>'Oral','duration'=>'30 days','quantity'=>'30 tablets','instructions'=>'Take with or without food.','priority'=>'Routine','status'=>'Pending','drug_interaction'=>'None detected'],
        ['rx_id'=>'RX-2026-006','patient_name'=>'Crisanto Valenzuela','patient_id'=>'P-2026-0006','age'=>41,'gender'=>'Male','allergies'=>'None Known','doctor'=>'Dr. Michael Reyes, MD','specialty'=>'Internal Medicine','rx_date'=>'2026-08-28','medicine'=>'Metformin 500mg','generic'=>'Metformin','dosage'=>'500mg','frequency'=>'Twice daily','route'=>'Oral','duration'=>'30 days','quantity'=>'60 tablets','instructions'=>'Take with meals to reduce GI upset.','priority'=>'Routine','status'=>'Under Verification','drug_interaction'=>'None detected'],
        ['rx_id'=>'RX-2026-007','patient_name'=>'Kristine Joy Garcia','patient_id'=>'P-2026-0007','age'=>29,'gender'=>'Female','allergies'=>'Aspirin','doctor'=>'Dr. Gabriel Mercado, MD','specialty'=>'Emergency Medicine','rx_date'=>'2026-08-28','medicine'=>'Paracetamol 500mg','generic'=>'Paracetamol','dosage'=>'500mg','frequency'=>'Every 6 hours','route'=>'Oral','duration'=>'3 days','quantity'=>'12 tablets','instructions'=>'Take as needed for pain or fever.','priority'=>'Urgent','status'=>'Ready for Dispensing','drug_interaction'=>'None detected'],
        ['rx_id'=>'RX-2026-008','patient_name'=>'Leandro Bautista','patient_id'=>'P-2026-0008','age'=>52,'gender'=>'Male','allergies'=>'None Known','doctor'=>'Dr. Victoria Gomez, MD','specialty'=>'Gastroenterology','rx_date'=>'2026-08-27','medicine'=>'Omeprazole 20mg','generic'=>'Omeprazole','dosage'=>'20mg','frequency'=>'Once daily','route'=>'Oral','duration'=>'14 days','quantity'=>'14 capsules','instructions'=>'Take 30 minutes before breakfast.','priority'=>'Routine','status'=>'Dispensed','drug_interaction'=>'None detected'],
        ['rx_id'=>'RX-2026-009','patient_name'=>'Teresa May Aquino','patient_id'=>'P-2026-0009','age'=>38,'gender'=>'Female','allergies'=>'Codeine','doctor'=>'Dr. Rafael Cruz, MD','specialty'=>'General Surgery','rx_date'=>'2026-08-28','medicine'=>'Mefenamic Acid 500mg','generic'=>'Mefenamic Acid','dosage'=>'500mg','frequency'=>'3 times daily','route'=>'Oral','duration'=>'5 days','quantity'=>'15 capsules','instructions'=>'Take after meals. Not for long-term use.','priority'=>'Routine','status'=>'Verified','drug_interaction'=>'None detected'],
        ['rx_id'=>'RX-2026-010','patient_name'=>'Gabriel Mendoza','patient_id'=>'P-2026-0010','age'=>63,'gender'=>'Male','allergies'=>'None Known','doctor'=>'Dr. Luisa Fernandez, MD','specialty'=>'Pulmonology','rx_date'=>'2026-08-28','medicine'=>'Salbutamol 2mg','generic'=>'Salbutamol','dosage'=>'2mg','frequency'=>'3 times daily','route'=>'Oral','duration'=>'7 days','quantity'=>'21 tablets','instructions'=>'Take regularly. Do not exceed dosage.','priority'=>'Urgent','status'=>'Pending','drug_interaction'=>'None detected'],
        ['rx_id'=>'RX-2026-011','patient_name'=>'Rosanna Cortez','patient_id'=>'P-2026-0011','age'=>49,'gender'=>'Female','allergies'=>'None Known','doctor'=>'Dr. Sophia Ramos, MD','specialty'=>'Endocrinology','rx_date'=>'2026-08-27','medicine'=>'Glibenclamide 5mg','generic'=>'Glibenclamide','dosage'=>'5mg','frequency'=>'Once daily with breakfast','route'=>'Oral','duration'=>'30 days','quantity'=>'30 tablets','instructions'=>'Take with morning meal.','priority'=>'Routine','status'=>'Dispensed','drug_interaction'=>'None detected'],
        ['rx_id'=>'RX-2026-012','patient_name'=>'Mark Anthony Ramos','patient_id'=>'P-2026-0012','age'=>19,'gender'=>'Male','allergies'=>'None Known','doctor'=>'Dr. Miguel Santos, MD','specialty'=>'Infectious Disease','rx_date'=>'2026-08-28','medicine'=>'Azithromycin 500mg','generic'=>'Azithromycin','dosage'=>'500mg','frequency'=>'Once daily','route'=>'Oral','duration'=>'5 days','quantity'=>'5 tablets','instructions'=>'Complete full course. Take 1 hour before meals.','priority'=>'Routine','status'=>'Pending','drug_interaction'=>'None detected'],
        ['rx_id'=>'RX-2026-013','patient_name'=>'Florencia Magpayo','patient_id'=>'P-2026-0013','age'=>72,'gender'=>'Female','allergies'=>'Tetracycline','doctor'=>'Dr. Carla Hernandez, MD','specialty'=>'Geriatrics','rx_date'=>'2026-08-28','medicine'=>'Losartan 50mg','generic'=>'Losartan','dosage'=>'50mg','frequency'=>'Once daily','route'=>'Oral','duration'=>'30 days','quantity'=>'30 tablets','instructions'=>'Monitor blood pressure regularly.','priority'=>'Routine','status'=>'Under Verification','drug_interaction'=>'None detected'],
        ['rx_id'=>'RX-2026-014','patient_name'=>'Danilo Ocampo','patient_id'=>'P-2026-0014','age'=>55,'gender'=>'Male','allergies'=>'None Known','doctor'=>'Dr. Michael Reyes, MD','specialty'=>'Internal Medicine','rx_date'=>'2026-08-28','medicine'=>'Atorvastatin 20mg','generic'=>'Atorvastatin','dosage'=>'20mg','frequency'=>'Once at bedtime','route'=>'Oral','duration'=>'30 days','quantity'=>'30 tablets','instructions'=>'Take at bedtime. Avoid grapefruit.','priority'=>'Routine','status'=>'Ready for Dispensing','drug_interaction'=>'None detected'],
        ['rx_id'=>'RX-2026-015','patient_name'=>'Shirley Mae Dela Rosa','patient_id'=>'P-2026-0015','age'=>33,'gender'=>'Female','allergies'=>'Ibuprofen','doctor'=>'Dr. Patricia Lim, MD','specialty'=>'OB-GYN','rx_date'=>'2026-08-28','medicine'=>'Folic Acid 5mg','generic'=>'Folic Acid','dosage'=>'5mg','frequency'=>'Once daily','route'=>'Oral','duration'=>'30 days','quantity'=>'30 tablets','instructions'=>'Take daily without regard to meals.','priority'=>'Routine','status'=>'Dispensed','drug_interaction'=>'None detected'],
        ['rx_id'=>'RX-2026-016','patient_name'=>'Ernesto Castillo','patient_id'=>'P-2026-0016','age'=>61,'gender'=>'Male','allergies'=>'None Known','doctor'=>'Dr. Antonio Mendoza, MD','specialty'=>'Cardiology','rx_date'=>'2026-08-28','medicine'=>'Isosorbide Mononitrate 30mg','generic'=>'Isosorbide Mononitrate','dosage'=>'30mg','frequency'=>'Once daily in the morning','route'=>'Oral','duration'=>'30 days','quantity'=>'30 tablets','instructions'=>'Take in morning. Avoid sudden stop.','priority'=>'STAT','status'=>'Verified','drug_interaction'=>'Sildenafil – CONTRAINDICATED'],
        ['rx_id'=>'RX-2026-017','patient_name'=>'Lourdes Panganiban','patient_id'=>'P-2026-0017','age'=>44,'gender'=>'Female','allergies'=>'Erythromycin','doctor'=>'Dr. Bernadette Ocampo, MD','specialty'=>'Dermatology','rx_date'=>'2026-08-27','medicine'=>'Cetirizine 10mg','generic'=>'Cetirizine','dosage'=>'10mg','frequency'=>'Once daily at bedtime','route'=>'Oral','duration'=>'14 days','quantity'=>'14 tablets','instructions'=>'May cause drowsiness. Avoid driving.','priority'=>'Routine','status'=>'Dispensed','drug_interaction'=>'None detected'],
        ['rx_id'=>'RX-2026-018','patient_name'=>'Renato Villanueva','patient_id'=>'P-2026-0018','age'=>37,'gender'=>'Male','allergies'=>'None Known','doctor'=>'Dr. Gabriel Mercado, MD','specialty'=>'Emergency Medicine','rx_date'=>'2026-08-28','medicine'=>'Tramadol 50mg','generic'=>'Tramadol','dosage'=>'50mg','frequency'=>'Every 8 hours','route'=>'Oral','duration'=>'5 days','quantity'=>'15 tablets','instructions'=>'Take after meals. Do not crush.','priority'=>'Urgent','status'=>'Ready for Dispensing','drug_interaction'=>'None detected'],
        ['rx_id'=>'RX-2026-019','patient_name'=>'Corazon Enriquez','patient_id'=>'P-2026-0019','age'=>56,'gender'=>'Female','allergies'=>'None Known','doctor'=>'Dr. Luisa Fernandez, MD','specialty'=>'Pulmonology','rx_date'=>'2026-08-28','medicine'=>'Montelukast 10mg','generic'=>'Montelukast','dosage'=>'10mg','frequency'=>'Once daily at bedtime','route'=>'Oral','duration'=>'30 days','quantity'=>'30 tablets','instructions'=>'Take regularly, even when feeling well.','priority'=>'Routine','status'=>'Pending','drug_interaction'=>'None detected'],
        ['rx_id'=>'RX-2026-020','patient_name'=>'Benedicto Soria','patient_id'=>'P-2026-0020','age'=>48,'gender'=>'Male','allergies'=>'Morphine','doctor'=>'Dr. Ricardo Manalang, MD','specialty'=>'Pain Management','rx_date'=>'2026-08-28','medicine'=>'Pregabalin 75mg','generic'=>'Pregabalin','dosage'=>'75mg','frequency'=>'Twice daily','route'=>'Oral','duration'=>'30 days','quantity'=>'60 capsules','instructions'=>'Titrate dose gradually. Avoid alcohol.','priority'=>'Routine','status'=>'Under Verification','drug_interaction'=>'None detected'],
        ['rx_id'=>'RX-2026-021','patient_name'=>'Maricel Tolentino','patient_id'=>'P-2026-0021','age'=>27,'gender'=>'Female','allergies'=>'None Known','doctor'=>'Dr. Elena Villanueva, MD','specialty'=>'Obstetrics','rx_date'=>'2026-08-27','medicine'=>'Calcium Carbonate 500mg','generic'=>'Calcium Carbonate','dosage'=>'500mg','frequency'=>'3 times daily','route'=>'Oral','duration'=>'30 days','quantity'=>'90 tablets','instructions'=>'Take with meals for better absorption.','priority'=>'Routine','status'=>'Dispensed','drug_interaction'=>'None detected'],
        ['rx_id'=>'RX-2026-022','patient_name'=>'Alfredo Navarro','patient_id'=>'P-2026-0022','age'=>70,'gender'=>'Male','allergies'=>'None Known','doctor'=>'Dr. Carlos Tan, MD','specialty'=>'Nephrology','rx_date'=>'2026-08-28','medicine'=>'Furosemide 40mg','generic'=>'Furosemide','dosage'=>'40mg','frequency'=>'Once daily in the morning','route'=>'Oral','duration'=>'30 days','quantity'=>'30 tablets','instructions'=>'Take in the morning. Monitor potassium.','priority'=>'Routine','status'=>'Pending','drug_interaction'=>'None detected'],
        ['rx_id'=>'RX-2026-023','patient_name'=>'Josephine Arceo','patient_id'=>'P-2026-0023','age'=>42,'gender'=>'Female','allergies'=>'Amoxicillin','doctor'=>'Dr. Victoria Gomez, MD','specialty'=>'Gastroenterology','rx_date'=>'2026-08-28','medicine'=>'Clarithromycin 500mg','generic'=>'Clarithromycin','dosage'=>'500mg','frequency'=>'Twice daily','route'=>'Oral','duration'=>'14 days','quantity'=>'28 tablets','instructions'=>'Take with food. Complete full course.','priority'=>'Routine','status'=>'Verified','drug_interaction'=>'None detected'],
        ['rx_id'=>'RX-2026-024','patient_name'=>'Christopher Evangelista','patient_id'=>'P-2026-0024','age'=>31,'gender'=>'Male','allergies'=>'None Known','doctor'=>'Dr. Miguel Santos, MD','specialty'=>'Infectious Disease','rx_date'=>'2026-08-28','medicine'=>'Doxycycline 100mg','generic'=>'Doxycycline','dosage'=>'100mg','frequency'=>'Twice daily','route'=>'Oral','duration'=>'10 days','quantity'=>'20 capsules','instructions'=>'Take with large glass of water. Avoid dairy 2hr before/after.','priority'=>'Routine','status'=>'Pending','drug_interaction'=>'None detected'],
        ['rx_id'=>'RX-2026-025','patient_name'=>'Remedios Cabrera','patient_id'=>'P-2026-0025','age'=>64,'gender'=>'Female','allergies'=>'Aspirin','doctor'=>'Dr. Sophia Ramos, MD','specialty'=>'Endocrinology','rx_date'=>'2026-08-27','medicine'=>'Insulin Glargine 10 Units','generic'=>'Insulin Glargine','dosage'=>'10 IU','frequency'=>'Once daily at bedtime','route'=>'Subcutaneous','duration'=>'30 days','quantity'=>'1 vial (10mL)','instructions'=>'Inject subcutaneously. Rotate injection sites.','priority'=>'STAT','status'=>'Dispensed','drug_interaction'=>'None detected'],
        ['rx_id'=>'RX-2026-026','patient_name'=>'Nestor Abaya','patient_id'=>'P-2026-0026','age'=>53,'gender'=>'Male','allergies'=>'None Known','doctor'=>'Dr. Michael Reyes, MD','specialty'=>'Internal Medicine','rx_date'=>'2026-08-28','medicine'=>'Lisinopril 10mg','generic'=>'Lisinopril','dosage'=>'10mg','frequency'=>'Once daily','route'=>'Oral','duration'=>'30 days','quantity'=>'30 tablets','instructions'=>'Monitor blood pressure. Report dry cough.','priority'=>'Routine','status'=>'Pending','drug_interaction'=>'None detected'],
        ['rx_id'=>'RX-2026-027','patient_name'=>'Glenda Lacson','patient_id'=>'P-2026-0027','age'=>36,'gender'=>'Female','allergies'=>'None Known','doctor'=>'Dr. Patricia Lim, MD','specialty'=>'OB-GYN','rx_date'=>'2026-08-28','medicine'=>'Metronidazole 500mg','generic'=>'Metronidazole','dosage'=>'500mg','frequency'=>'3 times daily','route'=>'Oral','duration'=>'7 days','quantity'=>'21 tablets','instructions'=>'Take after meals. Avoid alcohol during treatment.','priority'=>'Routine','status'=>'Under Verification','drug_interaction'=>'Alcohol – AVOID'],
        ['rx_id'=>'RX-2026-028','patient_name'=>'Victorino Samonte','patient_id'=>'P-2026-0028','age'=>59,'gender'=>'Male','allergies'=>'NSAIDs','doctor'=>'Dr. Antonio Mendoza, MD','specialty'=>'Cardiology','rx_date'=>'2026-08-28','medicine'=>'Bisoprolol 5mg','generic'=>'Bisoprolol','dosage'=>'5mg','frequency'=>'Once daily','route'=>'Oral','duration'=>'30 days','quantity'=>'30 tablets','instructions'=>'Do not stop abruptly. Monitor heart rate.','priority'=>'Routine','status'=>'Ready for Dispensing','drug_interaction'=>'None detected'],
        ['rx_id'=>'RX-2026-029','patient_name'=>'Carmelita Buendia','patient_id'=>'P-2026-0029','age'=>46,'gender'=>'Female','allergies'=>'None Known','doctor'=>'Dr. Bernadette Ocampo, MD','specialty'=>'Dermatology','rx_date'=>'2026-08-27','medicine'=>'Loratadine 10mg','generic'=>'Loratadine','dosage'=>'10mg','frequency'=>'Once daily','route'=>'Oral','duration'=>'14 days','quantity'=>'14 tablets','instructions'=>'Take once daily. Non-drowsy formula.','priority'=>'Routine','status'=>'Dispensed','drug_interaction'=>'None detected'],
        ['rx_id'=>'RX-2026-030','patient_name'=>'Filemon Ibañez','patient_id'=>'P-2026-0030','age'=>68,'gender'=>'Male','allergies'=>'Penicillin','doctor'=>'Dr. Luisa Fernandez, MD','specialty'=>'Pulmonology','rx_date'=>'2026-08-28','medicine'=>'Cotrimoxazole 960mg','generic'=>'Sulfamethoxazole + Trimethoprim','dosage'=>'960mg','frequency'=>'Twice daily','route'=>'Oral','duration'=>'14 days','quantity'=>'28 tablets','instructions'=>'Drink plenty of water. Complete full course.','priority'=>'Urgent','status'=>'Rejected','drug_interaction'=>'Warfarin – monitor INR'],
    ];
}

// ============================================================
// MEDICINE CATALOG (50 entries)
// ============================================================
function getDemoCatalog(): array
{
    return [
        ['med_id'=>'MED-001','generic_name'=>'Paracetamol','brand_name'=>'Biogesic','category'=>'Analgesic/Antipyretic','dosage_form'=>'Tablet','strength'=>'500mg','route'=>'Oral','unit'=>'Tablet','status'=>'Active'],
        ['med_id'=>'MED-002','generic_name'=>'Amoxicillin','brand_name'=>'Amoxil','category'=>'Antibiotic','dosage_form'=>'Capsule','strength'=>'500mg','route'=>'Oral','unit'=>'Capsule','status'=>'Active'],
        ['med_id'=>'MED-003','generic_name'=>'Ibuprofen','brand_name'=>'Advil','category'=>'NSAID','dosage_form'=>'Tablet','strength'=>'400mg','route'=>'Oral','unit'=>'Tablet','status'=>'Active'],
        ['med_id'=>'MED-004','generic_name'=>'Metformin','brand_name'=>'Glucophage','category'=>'Antidiabetic','dosage_form'=>'Tablet','strength'=>'500mg','route'=>'Oral','unit'=>'Tablet','status'=>'Active'],
        ['med_id'=>'MED-005','generic_name'=>'Loratadine','brand_name'=>'Claritin','category'=>'Antihistamine','dosage_form'=>'Tablet','strength'=>'10mg','route'=>'Oral','unit'=>'Tablet','status'=>'Active'],
        ['med_id'=>'MED-006','generic_name'=>'Omeprazole','brand_name'=>'Losec','category'=>'Proton Pump Inhibitor','dosage_form'=>'Capsule','strength'=>'20mg','route'=>'Oral','unit'=>'Capsule','status'=>'Active'],
        ['med_id'=>'MED-007','generic_name'=>'Azithromycin','brand_name'=>'Zithromax','category'=>'Antibiotic','dosage_form'=>'Tablet','strength'=>'500mg','route'=>'Oral','unit'=>'Tablet','status'=>'Active'],
        ['med_id'=>'MED-008','generic_name'=>'Amlodipine','brand_name'=>'Norvasc','category'=>'Calcium Channel Blocker','dosage_form'=>'Tablet','strength'=>'5mg','route'=>'Oral','unit'=>'Tablet','status'=>'Active'],
        ['med_id'=>'MED-009','generic_name'=>'Losartan','brand_name'=>'Cozaar','category'=>'ARB Antihypertensive','dosage_form'=>'Tablet','strength'=>'50mg','route'=>'Oral','unit'=>'Tablet','status'=>'Active'],
        ['med_id'=>'MED-010','generic_name'=>'Cetirizine','brand_name'=>'Zyrtec','category'=>'Antihistamine','dosage_form'=>'Tablet','strength'=>'10mg','route'=>'Oral','unit'=>'Tablet','status'=>'Active'],
        ['med_id'=>'MED-011','generic_name'=>'Atorvastatin','brand_name'=>'Lipitor','category'=>'Statin','dosage_form'=>'Tablet','strength'=>'20mg','route'=>'Oral','unit'=>'Tablet','status'=>'Active'],
        ['med_id'=>'MED-012','generic_name'=>'Clopidogrel','brand_name'=>'Plavix','category'=>'Antiplatelet','dosage_form'=>'Tablet','strength'=>'75mg','route'=>'Oral','unit'=>'Tablet','status'=>'Active'],
        ['med_id'=>'MED-013','generic_name'=>'Levothyroxine','brand_name'=>'Eltroxin','category'=>'Thyroid Hormone','dosage_form'=>'Tablet','strength'=>'50mcg','route'=>'Oral','unit'=>'Tablet','status'=>'Active'],
        ['med_id'=>'MED-014','generic_name'=>'Salbutamol','brand_name'=>'Ventolin','category'=>'Bronchodilator','dosage_form'=>'Tablet','strength'=>'2mg','route'=>'Oral','unit'=>'Tablet','status'=>'Active'],
        ['med_id'=>'MED-015','generic_name'=>'Salbutamol','brand_name'=>'Ventolin','category'=>'Bronchodilator','dosage_form'=>'Inhaler','strength'=>'100mcg/dose','route'=>'Inhalation','unit'=>'Inhaler','status'=>'Active'],
        ['med_id'=>'MED-016','generic_name'=>'Ferrous Sulfate','brand_name'=>'Feospan','category'=>'Iron Supplement','dosage_form'=>'Tablet','strength'=>'325mg','route'=>'Oral','unit'=>'Tablet','status'=>'Active'],
        ['med_id'=>'MED-017','generic_name'=>'Folic Acid','brand_name'=>'Folimax','category'=>'Vitamin/Supplement','dosage_form'=>'Tablet','strength'=>'5mg','route'=>'Oral','unit'=>'Tablet','status'=>'Active'],
        ['med_id'=>'MED-018','generic_name'=>'Vitamin C','brand_name'=>'Ceelin','category'=>'Vitamin/Supplement','dosage_form'=>'Tablet','strength'=>'500mg','route'=>'Oral','unit'=>'Tablet','status'=>'Active'],
        ['med_id'=>'MED-019','generic_name'=>'Glibenclamide','brand_name'=>'Daonil','category'=>'Antidiabetic','dosage_form'=>'Tablet','strength'=>'5mg','route'=>'Oral','unit'=>'Tablet','status'=>'Active'],
        ['med_id'=>'MED-020','generic_name'=>'Furosemide','brand_name'=>'Lasix','category'=>'Diuretic','dosage_form'=>'Tablet','strength'=>'40mg','route'=>'Oral','unit'=>'Tablet','status'=>'Active'],
        ['med_id'=>'MED-021','generic_name'=>'Lisinopril','brand_name'=>'Zestril','category'=>'ACE Inhibitor','dosage_form'=>'Tablet','strength'=>'10mg','route'=>'Oral','unit'=>'Tablet','status'=>'Active'],
        ['med_id'=>'MED-022','generic_name'=>'Bisoprolol','brand_name'=>'Concor','category'=>'Beta Blocker','dosage_form'=>'Tablet','strength'=>'5mg','route'=>'Oral','unit'=>'Tablet','status'=>'Active'],
        ['med_id'=>'MED-023','generic_name'=>'Montelukast','brand_name'=>'Singulair','category'=>'Leukotriene Inhibitor','dosage_form'=>'Tablet','strength'=>'10mg','route'=>'Oral','unit'=>'Tablet','status'=>'Active'],
        ['med_id'=>'MED-024','generic_name'=>'Mefenamic Acid','brand_name'=>'Ponstan','category'=>'NSAID','dosage_form'=>'Capsule','strength'=>'500mg','route'=>'Oral','unit'=>'Capsule','status'=>'Active'],
        ['med_id'=>'MED-025','generic_name'=>'Clarithromycin','brand_name'=>'Klacid','category'=>'Antibiotic','dosage_form'=>'Tablet','strength'=>'500mg','route'=>'Oral','unit'=>'Tablet','status'=>'Active'],
        ['med_id'=>'MED-026','generic_name'=>'Doxycycline','brand_name'=>'Vibramycin','category'=>'Antibiotic','dosage_form'=>'Capsule','strength'=>'100mg','route'=>'Oral','unit'=>'Capsule','status'=>'Active'],
        ['med_id'=>'MED-027','generic_name'=>'Pregabalin','brand_name'=>'Lyrica','category'=>'Anticonvulsant/Analgesic','dosage_form'=>'Capsule','strength'=>'75mg','route'=>'Oral','unit'=>'Capsule','status'=>'Active'],
        ['med_id'=>'MED-028','generic_name'=>'Tramadol','brand_name'=>'Ultram','category'=>'Opioid Analgesic','dosage_form'=>'Tablet','strength'=>'50mg','route'=>'Oral','unit'=>'Tablet','status'=>'Active'],
        ['med_id'=>'MED-029','generic_name'=>'Metronidazole','brand_name'=>'Flagyl','category'=>'Antibiotic/Antiprotozoal','dosage_form'=>'Tablet','strength'=>'500mg','route'=>'Oral','unit'=>'Tablet','status'=>'Active'],
        ['med_id'=>'MED-030','generic_name'=>'Cotrimoxazole','brand_name'=>'Bactrim','category'=>'Antibiotic','dosage_form'=>'Tablet','strength'=>'960mg','route'=>'Oral','unit'=>'Tablet','status'=>'Active'],
        ['med_id'=>'MED-031','generic_name'=>'Calcium Carbonate','brand_name'=>'Caltrate','category'=>'Calcium Supplement','dosage_form'=>'Tablet','strength'=>'500mg','route'=>'Oral','unit'=>'Tablet','status'=>'Active'],
        ['med_id'=>'MED-032','generic_name'=>'Insulin Glargine','brand_name'=>'Lantus','category'=>'Insulin','dosage_form'=>'Solution for Injection','strength'=>'100 IU/mL','route'=>'Subcutaneous','unit'=>'Vial (10mL)','status'=>'Active'],
        ['med_id'=>'MED-033','generic_name'=>'Insulin Regular','brand_name'=>'Humulin R','category'=>'Insulin','dosage_form'=>'Solution for Injection','strength'=>'100 IU/mL','route'=>'Subcutaneous','unit'=>'Vial (10mL)','status'=>'Active'],
        ['med_id'=>'MED-034','generic_name'=>'Isosorbide Mononitrate','brand_name'=>'Imdur','category'=>'Nitrate','dosage_form'=>'Tablet','strength'=>'30mg','route'=>'Oral','unit'=>'Tablet','status'=>'Active'],
        ['med_id'=>'MED-035','generic_name'=>'Warfarin','brand_name'=>'Coumadin','category'=>'Anticoagulant','dosage_form'=>'Tablet','strength'=>'2.5mg','route'=>'Oral','unit'=>'Tablet','status'=>'Active'],
        ['med_id'=>'MED-036','generic_name'=>'Digoxin','brand_name'=>'Lanoxin','category'=>'Cardiac Glycoside','dosage_form'=>'Tablet','strength'=>'0.25mg','route'=>'Oral','unit'=>'Tablet','status'=>'Active'],
        ['med_id'=>'MED-037','generic_name'=>'Spironolactone','brand_name'=>'Aldactone','category'=>'Potassium-Sparing Diuretic','dosage_form'=>'Tablet','strength'=>'25mg','route'=>'Oral','unit'=>'Tablet','status'=>'Active'],
        ['med_id'=>'MED-038','generic_name'=>'Pantoprazole','brand_name'=>'Protonix','category'=>'Proton Pump Inhibitor','dosage_form'=>'Tablet','strength'=>'40mg','route'=>'Oral','unit'=>'Tablet','status'=>'Active'],
        ['med_id'=>'MED-039','generic_name'=>'Fluconazole','brand_name'=>'Diflucan','category'=>'Antifungal','dosage_form'=>'Capsule','strength'=>'150mg','route'=>'Oral','unit'=>'Capsule','status'=>'Active'],
        ['med_id'=>'MED-040','generic_name'=>'Loperamide','brand_name'=>'Imodium','category'=>'Antidiarrheal','dosage_form'=>'Capsule','strength'=>'2mg','route'=>'Oral','unit'=>'Capsule','status'=>'Active'],
        ['med_id'=>'MED-041','generic_name'=>'Domperidone','brand_name'=>'Motilium','category'=>'Prokinetic/Antiemetic','dosage_form'=>'Tablet','strength'=>'10mg','route'=>'Oral','unit'=>'Tablet','status'=>'Active'],
        ['med_id'=>'MED-042','generic_name'=>'Ondansetron','brand_name'=>'Zofran','category'=>'Antiemetic','dosage_form'=>'Tablet','strength'=>'4mg','route'=>'Oral','unit'=>'Tablet','status'=>'Active'],
        ['med_id'=>'MED-043','generic_name'=>'Clindamycin','brand_name'=>'Dalacin','category'=>'Antibiotic','dosage_form'=>'Capsule','strength'=>'300mg','route'=>'Oral','unit'=>'Capsule','status'=>'Active'],
        ['med_id'=>'MED-044','generic_name'=>'Carbamazepine','brand_name'=>'Tegretol','category'=>'Anticonvulsant','dosage_form'=>'Tablet','strength'=>'200mg','route'=>'Oral','unit'=>'Tablet','status'=>'Active'],
        ['med_id'=>'MED-045','generic_name'=>'Allopurinol','brand_name'=>'Zyloprim','category'=>'Antigout','dosage_form'=>'Tablet','strength'=>'100mg','route'=>'Oral','unit'=>'Tablet','status'=>'Active'],
        ['med_id'=>'MED-046','generic_name'=>'Colchicine','brand_name'=>'Colcys','category'=>'Antigout','dosage_form'=>'Tablet','strength'=>'0.5mg','route'=>'Oral','unit'=>'Tablet','status'=>'Active'],
        ['med_id'=>'MED-047','generic_name'=>'Propranolol','brand_name'=>'Inderal','category'=>'Beta Blocker','dosage_form'=>'Tablet','strength'=>'40mg','route'=>'Oral','unit'=>'Tablet','status'=>'Active'],
        ['med_id'=>'MED-048','generic_name'=>'Captopril','brand_name'=>'Capoten','category'=>'ACE Inhibitor','dosage_form'=>'Tablet','strength'=>'25mg','route'=>'Oral','unit'=>'Tablet','status'=>'Inactive'],
        ['med_id'=>'MED-049','generic_name'=>'Ampicillin','brand_name'=>'Omnipen','category'=>'Antibiotic','dosage_form'=>'Capsule','strength'=>'500mg','route'=>'Oral','unit'=>'Capsule','status'=>'Active'],
        ['med_id'=>'MED-050','generic_name'=>'Ciprofloxacin','brand_name'=>'Ciprobay','category'=>'Antibiotic','dosage_form'=>'Tablet','strength'=>'500mg','route'=>'Oral','unit'=>'Tablet','status'=>'Active'],
    ];
}

// ============================================================
// INVENTORY (40 batches)
// ============================================================
function getDemoInventory(): array
{
    return [
        ['inv_id'=>'INV-001','medicine'=>'Amoxicillin 500mg','category'=>'Antibiotic','batch'=>'B-2026-011','supplier'=>'Zuellig Pharma','current_stock'=>120,'min_stock'=>50,'unit'=>'Capsule','mfg_date'=>'2025-06-01','expiry_date'=>'2027-12-31','status'=>'In Stock','unit_price'=>5.50],
        ['inv_id'=>'INV-002','medicine'=>'Paracetamol 500mg','category'=>'Analgesic','batch'=>'B-2026-012','supplier'=>'United Pharma','current_stock'=>35,'min_stock'=>100,'unit'=>'Tablet','mfg_date'=>'2025-08-01','expiry_date'=>'2027-08-31','status'=>'Low Stock','unit_price'=>2.00],
        ['inv_id'=>'INV-003','medicine'=>'Ibuprofen 400mg','category'=>'NSAID','batch'=>'B-2026-013','supplier'=>'Interphil Labs','current_stock'=>200,'min_stock'=>60,'unit'=>'Tablet','mfg_date'=>'2025-07-01','expiry_date'=>'2027-07-31','status'=>'In Stock','unit_price'=>4.00],
        ['inv_id'=>'INV-004','medicine'=>'Metformin 500mg','category'=>'Antidiabetic','batch'=>'B-2026-014','supplier'=>'Unilab','current_stock'=>180,'min_stock'=>80,'unit'=>'Tablet','mfg_date'=>'2025-05-01','expiry_date'=>'2027-05-31','status'=>'In Stock','unit_price'=>3.50],
        ['inv_id'=>'INV-005','medicine'=>'Loratadine 10mg','category'=>'Antihistamine','batch'=>'B-2026-015','supplier'=>'Bayer Philippines','current_stock'=>20,'min_stock'=>50,'unit'=>'Tablet','mfg_date'=>'2025-04-01','expiry_date'=>'2026-09-30','status'=>'Low Stock','unit_price'=>7.00],
        ['inv_id'=>'INV-006','medicine'=>'Omeprazole 20mg','category'=>'PPI','batch'=>'B-2026-016','supplier'=>'AstraZeneca PH','current_stock'=>90,'min_stock'=>40,'unit'=>'Capsule','mfg_date'=>'2025-09-01','expiry_date'=>'2027-09-30','status'=>'In Stock','unit_price'=>12.00],
        ['inv_id'=>'INV-007','medicine'=>'Azithromycin 500mg','category'=>'Antibiotic','batch'=>'B-2026-017','supplier'=>'Pfizer Philippines','current_stock'=>45,'min_stock'=>30,'unit'=>'Tablet','mfg_date'=>'2025-07-01','expiry_date'=>'2027-07-31','status'=>'In Stock','unit_price'=>85.00],
        ['inv_id'=>'INV-008','medicine'=>'Amlodipine 5mg','category'=>'Antihypertensive','batch'=>'B-2026-018','supplier'=>'Pfizer Philippines','current_stock'=>150,'min_stock'=>60,'unit'=>'Tablet','mfg_date'=>'2025-08-01','expiry_date'=>'2027-08-31','status'=>'In Stock','unit_price'=>8.00],
        ['inv_id'=>'INV-009','medicine'=>'Losartan 50mg','category'=>'Antihypertensive','batch'=>'B-2026-019','supplier'=>'Merck Sharp Dohme','current_stock'=>160,'min_stock'=>60,'unit'=>'Tablet','mfg_date'=>'2025-06-01','expiry_date'=>'2027-06-30','status'=>'In Stock','unit_price'=>15.00],
        ['inv_id'=>'INV-010','medicine'=>'Cetirizine 10mg','category'=>'Antihistamine','batch'=>'B-2026-020','supplier'=>'UCB Pharma','current_stock'=>25,'min_stock'=>50,'unit'=>'Tablet','mfg_date'=>'2025-03-01','expiry_date'=>'2026-10-15','status'=>'Low Stock','unit_price'=>9.00],
        ['inv_id'=>'INV-011','medicine'=>'Atorvastatin 20mg','category'=>'Statin','batch'=>'B-2026-021','supplier'=>'Pfizer Philippines','current_stock'=>130,'min_stock'=>50,'unit'=>'Tablet','mfg_date'=>'2025-08-01','expiry_date'=>'2027-08-31','status'=>'In Stock','unit_price'=>22.00],
        ['inv_id'=>'INV-012','medicine'=>'Clopidogrel 75mg','category'=>'Antiplatelet','batch'=>'B-2026-022','supplier'=>'Sanofi Philippines','current_stock'=>80,'min_stock'=>40,'unit'=>'Tablet','mfg_date'=>'2025-07-01','expiry_date'=>'2027-07-31','status'=>'In Stock','unit_price'=>28.00],
        ['inv_id'=>'INV-013','medicine'=>'Levothyroxine 50mcg','category'=>'Thyroid Hormone','batch'=>'B-2026-023','supplier'=>'Abbott Laboratories','current_stock'=>70,'min_stock'=>30,'unit'=>'Tablet','mfg_date'=>'2025-06-01','expiry_date'=>'2027-06-30','status'=>'In Stock','unit_price'=>18.00],
        ['inv_id'=>'INV-014','medicine'=>'Salbutamol 2mg','category'=>'Bronchodilator','batch'=>'B-2026-024','supplier'=>'GlaxoSmithKline PH','current_stock'=>0,'min_stock'=>40,'unit'=>'Tablet','mfg_date'=>'2025-01-01','expiry_date'=>'2027-01-31','status'=>'Out of Stock','unit_price'=>4.50],
        ['inv_id'=>'INV-015','medicine'=>'Ferrous Sulfate 325mg','category'=>'Iron Supplement','batch'=>'B-2026-025','supplier'=>'Unilab','current_stock'=>200,'min_stock'=>80,'unit'=>'Tablet','mfg_date'=>'2025-09-01','expiry_date'=>'2027-09-30','status'=>'In Stock','unit_price'=>3.00],
        ['inv_id'=>'INV-016','medicine'=>'Folic Acid 5mg','category'=>'Vitamin','batch'=>'B-2026-026','supplier'=>'Unilab','current_stock'=>250,'min_stock'=>100,'unit'=>'Tablet','mfg_date'=>'2025-09-01','expiry_date'=>'2027-09-30','status'=>'In Stock','unit_price'=>2.50],
        ['inv_id'=>'INV-017','medicine'=>'Vitamin C 500mg','category'=>'Vitamin','batch'=>'B-2025-021','supplier'=>'Unilab','current_stock'=>180,'min_stock'=>100,'unit'=>'Tablet','mfg_date'=>'2025-02-01','expiry_date'=>'2026-09-12','status'=>'Expiring Soon','unit_price'=>5.00],
        ['inv_id'=>'INV-018','medicine'=>'Glibenclamide 5mg','category'=>'Antidiabetic','batch'=>'B-2026-028','supplier'=>'Sanofi Philippines','current_stock'=>100,'min_stock'=>40,'unit'=>'Tablet','mfg_date'=>'2025-08-01','expiry_date'=>'2027-08-31','status'=>'In Stock','unit_price'=>6.50],
        ['inv_id'=>'INV-019','medicine'=>'Furosemide 40mg','category'=>'Diuretic','batch'=>'B-2026-029','supplier'=>'Unilab','current_stock'=>40,'min_stock'=>60,'unit'=>'Tablet','mfg_date'=>'2025-07-01','expiry_date'=>'2027-07-31','status'=>'Low Stock','unit_price'=>4.00],
        ['inv_id'=>'INV-020','medicine'=>'Lisinopril 10mg','category'=>'Antihypertensive','batch'=>'B-2026-030','supplier'=>'Zuellig Pharma','current_stock'=>110,'min_stock'=>50,'unit'=>'Tablet','mfg_date'=>'2025-08-01','expiry_date'=>'2027-08-31','status'=>'In Stock','unit_price'=>10.00],
        ['inv_id'=>'INV-021','medicine'=>'Bisoprolol 5mg','category'=>'Beta Blocker','batch'=>'B-2026-031','supplier'=>'Merck Philippines','current_stock'=>95,'min_stock'=>40,'unit'=>'Tablet','mfg_date'=>'2025-08-01','expiry_date'=>'2027-08-31','status'=>'In Stock','unit_price'=>14.00],
        ['inv_id'=>'INV-022','medicine'=>'Montelukast 10mg','category'=>'Leukotriene Inhibitor','batch'=>'B-2026-032','supplier'=>'Merck Sharp Dohme','current_stock'=>60,'min_stock'=>30,'unit'=>'Tablet','mfg_date'=>'2025-07-01','expiry_date'=>'2027-07-31','status'=>'In Stock','unit_price'=>45.00],
        ['inv_id'=>'INV-023','medicine'=>'Mefenamic Acid 500mg','category'=>'NSAID','batch'=>'B-2026-033','supplier'=>'Interphil Labs','current_stock'=>18,'min_stock'=>60,'unit'=>'Capsule','mfg_date'=>'2025-06-01','expiry_date'=>'2027-06-30','status'=>'Low Stock','unit_price'=>4.50],
        ['inv_id'=>'INV-024','medicine'=>'Clarithromycin 500mg','category'=>'Antibiotic','batch'=>'B-2026-034','supplier'=>'Abbott Laboratories','current_stock'=>55,'min_stock'=>30,'unit'=>'Tablet','mfg_date'=>'2025-08-01','expiry_date'=>'2027-08-31','status'=>'In Stock','unit_price'=>55.00],
        ['inv_id'=>'INV-025','medicine'=>'Doxycycline 100mg','category'=>'Antibiotic','batch'=>'B-2026-035','supplier'=>'Pfizer Philippines','current_stock'=>80,'min_stock'=>40,'unit'=>'Capsule','mfg_date'=>'2025-07-01','expiry_date'=>'2027-07-31','status'=>'In Stock','unit_price'=>18.00],
        ['inv_id'=>'INV-026','medicine'=>'Pregabalin 75mg','category'=>'Anticonvulsant','batch'=>'B-2026-036','supplier'=>'Pfizer Philippines','current_stock'=>30,'min_stock'=>20,'unit'=>'Capsule','mfg_date'=>'2025-08-01','expiry_date'=>'2027-08-31','status'=>'In Stock','unit_price'=>68.00],
        ['inv_id'=>'INV-027','medicine'=>'Tramadol 50mg','category'=>'Opioid Analgesic','batch'=>'B-2026-037','supplier'=>'Grunenthal Philippines','current_stock'=>22,'min_stock'=>30,'unit'=>'Tablet','mfg_date'=>'2025-07-01','expiry_date'=>'2027-07-31','status'=>'Low Stock','unit_price'=>22.00],
        ['inv_id'=>'INV-028','medicine'=>'Metronidazole 500mg','category'=>'Antibiotic','batch'=>'B-2026-038','supplier'=>'Sanofi Philippines','current_stock'=>140,'min_stock'=>60,'unit'=>'Tablet','mfg_date'=>'2025-08-01','expiry_date'=>'2027-08-31','status'=>'In Stock','unit_price'=>5.50],
        ['inv_id'=>'INV-029','medicine'=>'Calcium Carbonate 500mg','category'=>'Calcium Supplement','batch'=>'B-2026-039','supplier'=>'Wyeth Philippines','current_stock'=>320,'min_stock'=>100,'unit'=>'Tablet','mfg_date'=>'2025-09-01','expiry_date'=>'2027-09-30','status'=>'In Stock','unit_price'=>3.50],
        ['inv_id'=>'INV-030','medicine'=>'Insulin Glargine 100IU/mL','category'=>'Insulin','batch'=>'B-2026-040','supplier'=>'Sanofi Philippines','current_stock'=>15,'min_stock'=>10,'unit'=>'Vial','mfg_date'=>'2025-07-01','expiry_date'=>'2027-07-31','status'=>'In Stock','unit_price'=>850.00],
        ['inv_id'=>'INV-031','medicine'=>'Isosorbide Mononitrate 30mg','category'=>'Nitrate','batch'=>'B-2026-041','supplier'=>'AstraZeneca PH','current_stock'=>0,'min_stock'=>30,'unit'=>'Tablet','mfg_date'=>'2024-12-01','expiry_date'=>'2026-12-31','status'=>'Out of Stock','unit_price'=>35.00],
        ['inv_id'=>'INV-032','medicine'=>'Warfarin 2.5mg','category'=>'Anticoagulant','batch'=>'B-2026-042','supplier'=>'Bristol-Myers Squibb','current_stock'=>50,'min_stock'=>20,'unit'=>'Tablet','mfg_date'=>'2025-06-01','expiry_date'=>'2027-06-30','status'=>'In Stock','unit_price'=>25.00],
        ['inv_id'=>'INV-033','medicine'=>'Pantoprazole 40mg','category'=>'PPI','batch'=>'B-2026-043','supplier'=>'Wyeth Philippines','current_stock'=>85,'min_stock'=>40,'unit'=>'Tablet','mfg_date'=>'2025-08-01','expiry_date'=>'2027-08-31','status'=>'In Stock','unit_price'=>18.00],
        ['inv_id'=>'INV-034','medicine'=>'Fluconazole 150mg','category'=>'Antifungal','batch'=>'B-2026-044','supplier'=>'Pfizer Philippines','current_stock'=>12,'min_stock'=>20,'unit'=>'Capsule','mfg_date'=>'2025-05-01','expiry_date'=>'2026-09-25','status'=>'Low Stock','unit_price'=>95.00],
        ['inv_id'=>'INV-035','medicine'=>'Cetirizine 10mg','category'=>'Antihistamine','batch'=>'B-2025-010','supplier'=>'UCB Pharma','current_stock'=>5,'min_stock'=>50,'unit'=>'Tablet','mfg_date'=>'2024-10-01','expiry_date'=>'2026-08-20','status'=>'Expired','unit_price'=>9.00],
        ['inv_id'=>'INV-036','medicine'=>'Domperidone 10mg','category'=>'Antiemetic','batch'=>'B-2026-045','supplier'=>'Janssen PH','current_stock'=>75,'min_stock'=>30,'unit'=>'Tablet','mfg_date'=>'2025-08-01','expiry_date'=>'2027-08-31','status'=>'In Stock','unit_price'=>8.50],
        ['inv_id'=>'INV-037','medicine'=>'Ondansetron 4mg','category'=>'Antiemetic','batch'=>'B-2026-046','supplier'=>'GlaxoSmithKline PH','current_stock'=>40,'min_stock'=>20,'unit'=>'Tablet','mfg_date'=>'2025-07-01','expiry_date'=>'2027-07-31','status'=>'In Stock','unit_price'=>48.00],
        ['inv_id'=>'INV-038','medicine'=>'Clindamycin 300mg','category'=>'Antibiotic','batch'=>'B-2026-047','supplier'=>'Pfizer Philippines','current_stock'=>60,'min_stock'=>30,'unit'=>'Capsule','mfg_date'=>'2025-08-01','expiry_date'=>'2027-08-31','status'=>'In Stock','unit_price'=>32.00],
        ['inv_id'=>'INV-039','medicine'=>'Allopurinol 100mg','category'=>'Antigout','batch'=>'B-2026-048','supplier'=>'Unilab','current_stock'=>120,'min_stock'=>50,'unit'=>'Tablet','mfg_date'=>'2025-09-01','expiry_date'=>'2027-09-30','status'=>'In Stock','unit_price'=>3.00],
        ['inv_id'=>'INV-040','medicine'=>'Ciprofloxacin 500mg','category'=>'Antibiotic','batch'=>'B-2026-049','supplier'=>'Bayer Philippines','current_stock'=>28,'min_stock'=>40,'unit'=>'Tablet','mfg_date'=>'2025-07-01','expiry_date'=>'2026-09-08','status'=>'Low Stock','unit_price'=>30.00],
    ];
}

// ============================================================
// DISPENSING RECORDS (20 entries)
// ============================================================
function getDemoDispensingRecords(): array
{
    return [
        ['disp_id'=>'DISP-2026-001','rx_id'=>'RX-2026-004','patient_name'=>'Angelica Mae Reyes','medicine'=>'Levothyroxine 50mcg','qty_prescribed'=>30,'qty_dispensed'=>30,'disp_date'=>'2026-08-27','dispensed_by'=>'Maria Santos, RPh','instructions'=>'Take 30 min before breakfast','notes'=>'Counseled patient on medication adherence','status'=>'Dispensed'],
        ['disp_id'=>'DISP-2026-002','rx_id'=>'RX-2026-008','patient_name'=>'Leandro Bautista','medicine'=>'Omeprazole 20mg','qty_prescribed'=>14,'qty_dispensed'=>14,'disp_date'=>'2026-08-27','dispensed_by'=>'Maria Santos, RPh','instructions'=>'Take 30 min before breakfast','notes'=>'','status'=>'Dispensed'],
        ['disp_id'=>'DISP-2026-003','rx_id'=>'RX-2026-011','patient_name'=>'Rosanna Cortez','medicine'=>'Glibenclamide 5mg','qty_prescribed'=>30,'qty_dispensed'=>30,'disp_date'=>'2026-08-27','dispensed_by'=>'Maria Santos, RPh','instructions'=>'Take with morning meal','notes'=>'Patient instructed on hypoglycemia signs','status'=>'Dispensed'],
        ['disp_id'=>'DISP-2026-004','rx_id'=>'RX-2026-015','patient_name'=>'Shirley Mae Dela Rosa','medicine'=>'Folic Acid 5mg','qty_prescribed'=>30,'qty_dispensed'=>30,'disp_date'=>'2026-08-27','dispensed_by'=>'Juan Dela Cruz, RPh','instructions'=>'Take once daily','notes'=>'','status'=>'Dispensed'],
        ['disp_id'=>'DISP-2026-005','rx_id'=>'RX-2026-017','patient_name'=>'Lourdes Panganiban','medicine'=>'Cetirizine 10mg','qty_prescribed'=>14,'qty_dispensed'=>14,'disp_date'=>'2026-08-27','dispensed_by'=>'Maria Santos, RPh','instructions'=>'Take at bedtime','notes'=>'Advised about drowsiness','status'=>'Dispensed'],
        ['disp_id'=>'DISP-2026-006','rx_id'=>'RX-2026-021','patient_name'=>'Maricel Tolentino','medicine'=>'Calcium Carbonate 500mg','qty_prescribed'=>90,'qty_dispensed'=>90,'disp_date'=>'2026-08-27','dispensed_by'=>'Maria Santos, RPh','instructions'=>'Take with meals','notes'=>'','status'=>'Dispensed'],
        ['disp_id'=>'DISP-2026-007','rx_id'=>'RX-2026-025','patient_name'=>'Remedios Cabrera','medicine'=>'Insulin Glargine 100IU/mL','qty_prescribed'=>1,'qty_dispensed'=>1,'disp_date'=>'2026-08-27','dispensed_by'=>'Maria Santos, RPh','instructions'=>'Inject subcutaneously at bedtime','notes'=>'Demonstrated injection technique','status'=>'Dispensed'],
        ['disp_id'=>'DISP-2026-008','rx_id'=>'RX-2026-029','patient_name'=>'Carmelita Buendia','medicine'=>'Loratadine 10mg','qty_prescribed'=>14,'qty_dispensed'=>14,'disp_date'=>'2026-08-27','dispensed_by'=>'Juan Dela Cruz, RPh','instructions'=>'Take once daily','notes'=>'','status'=>'Dispensed'],
        ['disp_id'=>'DISP-2026-009','rx_id'=>'RX-2026-002','patient_name'=>'Maria Clara Santos','medicine'=>'Ferrous Sulfate 325mg','qty_prescribed'=>30,'qty_dispensed'=>30,'disp_date'=>'2026-08-28','dispensed_by'=>'Maria Santos, RPh','instructions'=>'Take with orange juice','notes'=>'Counseled on stool discoloration','status'=>'Dispensed'],
        ['disp_id'=>'DISP-2026-010','rx_id'=>'RX-2026-009','patient_name'=>'Teresa May Aquino','medicine'=>'Mefenamic Acid 500mg','qty_prescribed'=>15,'qty_dispensed'=>15,'disp_date'=>'2026-08-28','dispensed_by'=>'Maria Santos, RPh','instructions'=>'Take after meals','notes'=>'','status'=>'Dispensed'],
        ['disp_id'=>'DISP-2026-011','rx_id'=>'RX-2026-023','patient_name'=>'Josephine Arceo','medicine'=>'Clarithromycin 500mg','qty_prescribed'=>28,'qty_dispensed'=>28,'disp_date'=>'2026-08-28','dispensed_by'=>'Maria Santos, RPh','instructions'=>'Take with food','notes'=>'Counseled on completing course','status'=>'Dispensed'],
        ['disp_id'=>'DISP-2026-012','rx_id'=>'RX-2026-014','patient_name'=>'Danilo Ocampo','medicine'=>'Atorvastatin 20mg','qty_prescribed'=>30,'qty_dispensed'=>30,'disp_date'=>'2026-08-28','dispensed_by'=>'Maria Santos, RPh','instructions'=>'Take at bedtime','notes'=>'Advised to avoid grapefruit','status'=>'Dispensed'],
        ['disp_id'=>'DISP-2026-013','rx_id'=>'RX-2026-016','patient_name'=>'Ernesto Castillo','medicine'=>'Isosorbide Mononitrate 30mg','qty_prescribed'=>30,'qty_dispensed'=>0,'disp_date'=>'2026-08-28','dispensed_by'=>'Maria Santos, RPh','instructions'=>'—','notes'=>'Out of stock – patient referred back to physician','status'=>'On Hold'],
        ['disp_id'=>'DISP-2026-014','rx_id'=>'RX-2026-028','patient_name'=>'Victorino Samonte','medicine'=>'Bisoprolol 5mg','qty_prescribed'=>30,'qty_dispensed'=>30,'disp_date'=>'2026-08-28','dispensed_by'=>'Maria Santos, RPh','instructions'=>'Do not stop abruptly','notes'=>'Reminded to monitor heart rate','status'=>'Dispensed'],
        ['disp_id'=>'DISP-2026-015','rx_id'=>'RX-2026-006','patient_name'=>'Crisanto Valenzuela','medicine'=>'Metformin 500mg','qty_prescribed'=>60,'qty_dispensed'=>60,'disp_date'=>'2026-08-28','dispensed_by'=>'Maria Santos, RPh','instructions'=>'Take with meals','notes'=>'','status'=>'Dispensed'],
        ['disp_id'=>'DISP-2026-016','rx_id'=>'RX-2026-003','patient_name'=>'Rodrigo Morales','medicine'=>'Clopidogrel 75mg','qty_prescribed'=>30,'qty_dispensed'=>30,'disp_date'=>'2026-08-28','dispensed_by'=>'Maria Santos, RPh','instructions'=>'Monitor for bleeding','notes'=>'Informed of drug interaction with Aspirin','status'=>'Dispensed'],
        ['disp_id'=>'DISP-2026-017','rx_id'=>'RX-2026-007','patient_name'=>'Kristine Joy Garcia','medicine'=>'Paracetamol 500mg','qty_prescribed'=>12,'qty_dispensed'=>12,'disp_date'=>'2026-08-28','dispensed_by'=>'Maria Santos, RPh','instructions'=>'Take as needed','notes'=>'','status'=>'Dispensed'],
        ['disp_id'=>'DISP-2026-018','rx_id'=>'RX-2026-018','patient_name'=>'Renato Villanueva','medicine'=>'Tramadol 50mg','qty_prescribed'=>15,'qty_dispensed'=>15,'disp_date'=>'2026-08-28','dispensed_by'=>'Maria Santos, RPh','instructions'=>'Take after meals','notes'=>'Controlled substance – recorded in logbook','status'=>'Dispensed'],
        ['disp_id'=>'DISP-2026-019','rx_id'=>'RX-2026-022','patient_name'=>'Alfredo Navarro','medicine'=>'Furosemide 40mg','qty_prescribed'=>30,'qty_dispensed'=>30,'disp_date'=>'2026-08-28','dispensed_by'=>'Maria Santos, RPh','instructions'=>'Take in the morning','notes'=>'Advised to monitor urine output','status'=>'Dispensed'],
        ['disp_id'=>'DISP-2026-020','rx_id'=>'RX-2026-012','patient_name'=>'Mark Anthony Ramos','medicine'=>'Azithromycin 500mg','qty_prescribed'=>5,'qty_dispensed'=>5,'disp_date'=>'2026-08-28','dispensed_by'=>'Maria Santos, RPh','instructions'=>'1 hour before meals','notes'=>'Counseled on Z-pack completion','status'=>'Dispensed'],
    ];
}

// ============================================================
// STOCK MOVEMENT (20 entries)
// ============================================================
function getDemoStockMovements(): array
{
    return [
        ['mov_id'=>'MOV-001','date'=>'2026-08-28','medicine'=>'Amoxicillin 500mg','batch'=>'B-2026-011','movement_type'=>'Dispensed','quantity'=>21,'prev_stock'=>141,'new_stock'=>120,'recorded_by'=>'Maria Santos, RPh','notes'=>'RX-2026-001'],
        ['mov_id'=>'MOV-002','date'=>'2026-08-28','medicine'=>'Clopidogrel 75mg','batch'=>'B-2026-022','movement_type'=>'Dispensed','quantity'=>30,'prev_stock'=>110,'new_stock'=>80,'recorded_by'=>'Maria Santos, RPh','notes'=>'RX-2026-003'],
        ['mov_id'=>'MOV-003','date'=>'2026-08-28','medicine'=>'Ferrous Sulfate 325mg','batch'=>'B-2026-025','movement_type'=>'Dispensed','quantity'=>30,'prev_stock'=>230,'new_stock'=>200,'recorded_by'=>'Maria Santos, RPh','notes'=>'RX-2026-002'],
        ['mov_id'=>'MOV-004','date'=>'2026-08-28','medicine'=>'Metformin 500mg','batch'=>'B-2026-014','movement_type'=>'Dispensed','quantity'=>60,'prev_stock'=>240,'new_stock'=>180,'recorded_by'=>'Maria Santos, RPh','notes'=>'RX-2026-006'],
        ['mov_id'=>'MOV-005','date'=>'2026-08-28','medicine'=>'Paracetamol 500mg','batch'=>'B-2026-012','movement_type'=>'Dispensed','quantity'=>12,'prev_stock'=>47,'new_stock'=>35,'recorded_by'=>'Maria Santos, RPh','notes'=>'RX-2026-007'],
        ['mov_id'=>'MOV-006','date'=>'2026-08-28','medicine'=>'Bisoprolol 5mg','batch'=>'B-2026-031','movement_type'=>'Dispensed','quantity'=>30,'prev_stock'=>125,'new_stock'=>95,'recorded_by'=>'Maria Santos, RPh','notes'=>'RX-2026-028'],
        ['mov_id'=>'MOV-007','date'=>'2026-08-27','medicine'=>'Paracetamol 500mg','batch'=>'B-2025-010','movement_type'=>'Disposed','quantity'=>50,'prev_stock'=>50,'new_stock'=>0,'recorded_by'=>'Maria Santos, RPh','notes'=>'Expired batch – disposal record created'],
        ['mov_id'=>'MOV-008','date'=>'2026-08-27','medicine'=>'Vitamin C 500mg','batch'=>'B-2025-021','movement_type'=>'Dispensed','quantity'=>30,'prev_stock'=>210,'new_stock'=>180,'recorded_by'=>'Maria Santos, RPh','notes'=>'RX-2026-021'],
        ['mov_id'=>'MOV-009','date'=>'2026-08-26','medicine'=>'Amoxicillin 500mg','batch'=>'B-2026-011','movement_type'=>'Stock-In','quantity'=>200,'prev_stock'=>0,'new_stock'=>200,'recorded_by'=>'Maria Santos, RPh','notes'=>'PO-2026-031 from Zuellig Pharma'],
        ['mov_id'=>'MOV-010','date'=>'2026-08-26','medicine'=>'Ibuprofen 400mg','batch'=>'B-2026-013','movement_type'=>'Stock-In','quantity'=>300,'prev_stock'=>0,'new_stock'=>300,'recorded_by'=>'Maria Santos, RPh','notes'=>'PO-2026-032 from Interphil Labs'],
        ['mov_id'=>'MOV-011','date'=>'2026-08-26','medicine'=>'Calcium Carbonate 500mg','batch'=>'B-2026-039','movement_type'=>'Stock-In','quantity'=>500,'prev_stock'=>0,'new_stock'=>500,'recorded_by'=>'Maria Santos, RPh','notes'=>'PO-2026-033 from Wyeth Philippines'],
        ['mov_id'=>'MOV-012','date'=>'2026-08-25','medicine'=>'Furosemide 40mg','batch'=>'B-2026-029','movement_type'=>'Dispensed','quantity'=>30,'prev_stock'=>70,'new_stock'=>40,'recorded_by'=>'Maria Santos, RPh','notes'=>'RX-2026-022'],
        ['mov_id'=>'MOV-013','date'=>'2026-08-25','medicine'=>'Loratadine 10mg','batch'=>'B-2026-015','movement_type'=>'Dispensed','quantity'=>14,'prev_stock'=>34,'new_stock'=>20,'recorded_by'=>'Maria Santos, RPh','notes'=>'RX-2026-029'],
        ['mov_id'=>'MOV-014','date'=>'2026-08-24','medicine'=>'Atorvastatin 20mg','batch'=>'B-2026-021','movement_type'=>'Dispensed','quantity'=>30,'prev_stock'=>160,'new_stock'=>130,'recorded_by'=>'Maria Santos, RPh','notes'=>'RX-2026-014'],
        ['mov_id'=>'MOV-015','date'=>'2026-08-24','medicine'=>'Omeprazole 20mg','batch'=>'B-2026-016','movement_type'=>'Dispensed','quantity'=>14,'prev_stock'=>104,'new_stock'=>90,'recorded_by'=>'Maria Santos, RPh','notes'=>'RX-2026-008'],
        ['mov_id'=>'MOV-016','date'=>'2026-08-23','medicine'=>'Mefenamic Acid 500mg','batch'=>'B-2026-033','movement_type'=>'Dispensed','quantity'=>30,'prev_stock'=>48,'new_stock'=>18,'recorded_by'=>'Maria Santos, RPh','notes'=>'RX-2026-009, RX-2026-previous'],
        ['mov_id'=>'MOV-017','date'=>'2026-08-23','medicine'=>'Tramadol 50mg','batch'=>'B-2026-037','movement_type'=>'Dispensed','quantity'=>15,'prev_stock'=>37,'new_stock'=>22,'recorded_by'=>'Maria Santos, RPh','notes'=>'RX-2026-018 – controlled substance'],
        ['mov_id'=>'MOV-018','date'=>'2026-08-22','medicine'=>'Cetirizine 10mg','batch'=>'B-2025-010','movement_type'=>'Disposed','quantity'=>45,'prev_stock'=>50,'new_stock'=>5,'recorded_by'=>'Maria Santos, RPh','notes'=>'Expired – disposed per protocol'],
        ['mov_id'=>'MOV-019','date'=>'2026-08-22','medicine'=>'Azithromycin 500mg','batch'=>'B-2026-017','movement_type'=>'Stock-In','quantity'=>100,'prev_stock'=>0,'new_stock'=>100,'recorded_by'=>'Maria Santos, RPh','notes'=>'PO-2026-028 from Pfizer Philippines'],
        ['mov_id'=>'MOV-020','date'=>'2026-08-21','medicine'=>'Losartan 50mg','batch'=>'B-2026-019','movement_type'=>'Adjustment','quantity'=>-5,'prev_stock'=>165,'new_stock'=>160,'recorded_by'=>'Maria Santos, RPh','notes'=>'Physical count adjustment – overcount corrected'],
    ];
}

// ============================================================
// LOW-STOCK ALERTS
// ============================================================
function getDemoLowStockAlerts(): array
{
    return [
        ['medicine'=>'Paracetamol 500mg','batch'=>'B-2026-012','current_stock'=>35,'min_stock'=>100,'unit'=>'Tablet','category'=>'Analgesic','supplier'=>'United Pharma'],
        ['medicine'=>'Loratadine 10mg','batch'=>'B-2026-015','current_stock'=>20,'min_stock'=>50,'unit'=>'Tablet','category'=>'Antihistamine','supplier'=>'Bayer Philippines'],
        ['medicine'=>'Cetirizine 10mg','batch'=>'B-2026-020','current_stock'=>25,'min_stock'=>50,'unit'=>'Tablet','category'=>'Antihistamine','supplier'=>'UCB Pharma'],
        ['medicine'=>'Furosemide 40mg','batch'=>'B-2026-029','current_stock'=>40,'min_stock'=>60,'unit'=>'Tablet','category'=>'Diuretic','supplier'=>'Unilab'],
        ['medicine'=>'Mefenamic Acid 500mg','batch'=>'B-2026-033','current_stock'=>18,'min_stock'=>60,'unit'=>'Capsule','category'=>'NSAID','supplier'=>'Interphil Labs'],
        ['medicine'=>'Tramadol 50mg','batch'=>'B-2026-037','current_stock'=>22,'min_stock'=>30,'unit'=>'Tablet','category'=>'Opioid Analgesic','supplier'=>'Grunenthal Philippines'],
        ['medicine'=>'Fluconazole 150mg','batch'=>'B-2026-044','current_stock'=>12,'min_stock'=>20,'unit'=>'Capsule','category'=>'Antifungal','supplier'=>'Pfizer Philippines'],
        ['medicine'=>'Ciprofloxacin 500mg','batch'=>'B-2026-049','current_stock'=>28,'min_stock'=>40,'unit'=>'Tablet','category'=>'Antibiotic','supplier'=>'Bayer Philippines'],
        ['medicine'=>'Salbutamol 2mg','batch'=>'B-2026-024','current_stock'=>0,'min_stock'=>40,'unit'=>'Tablet','category'=>'Bronchodilator','supplier'=>'GlaxoSmithKline PH'],
        ['medicine'=>'Isosorbide Mononitrate 30mg','batch'=>'B-2026-041','current_stock'=>0,'min_stock'=>30,'unit'=>'Tablet','category'=>'Nitrate','supplier'=>'AstraZeneca PH'],
    ];
}

// ============================================================
// EXPIRY ALERTS
// ============================================================
function getDemoExpiryAlerts(): array
{
    return [
        ['medicine'=>'Vitamin C 500mg','batch'=>'B-2025-021','expiry_date'=>'2026-09-12','days_left'=>15,'category'=>'Vitamin','current_stock'=>180,'status'=>'Expiring Soon'],
        ['medicine'=>'Loratadine 10mg','batch'=>'B-2026-015','expiry_date'=>'2026-09-30','days_left'=>33,'category'=>'Antihistamine','current_stock'=>20,'status'=>'Expiring Soon'],
        ['medicine'=>'Cetirizine 10mg','batch'=>'B-2026-020','expiry_date'=>'2026-10-15','days_left'=>48,'category'=>'Antihistamine','current_stock'=>25,'status'=>'Expiring Soon'],
        ['medicine'=>'Fluconazole 150mg','batch'=>'B-2026-044','expiry_date'=>'2026-09-25','days_left'=>28,'category'=>'Antifungal','current_stock'=>12,'status'=>'Expiring Soon'],
        ['medicine'=>'Ciprofloxacin 500mg','batch'=>'B-2026-049','expiry_date'=>'2026-09-08','days_left'=>11,'category'=>'Antibiotic','current_stock'=>28,'status'=>'Expiring Soon'],
        ['medicine'=>'Cetirizine 10mg','batch'=>'B-2025-010','expiry_date'=>'2026-08-20','days_left'=>-8,'category'=>'Antihistamine','current_stock'=>5,'status'=>'Expired'],
        ['medicine'=>'Isosorbide Mononitrate 30mg','batch'=>'B-2026-041','expiry_date'=>'2026-12-31','days_left'=>125,'category'=>'Nitrate','current_stock'=>0,'status'=>'Expiring Soon'],
        ['medicine'=>'Salbutamol 2mg','batch'=>'B-2024-010','expiry_date'=>'2026-09-01','days_left'=>4,'category'=>'Bronchodilator','current_stock'=>0,'status'=>'Expired'],
        ['medicine'=>'Cotrimoxazole 960mg','batch'=>'B-2025-009','expiry_date'=>'2026-09-20','days_left'=>23,'category'=>'Antibiotic','current_stock'=>15,'status'=>'Expiring Soon'],
        ['medicine'=>'Ampicillin 500mg','batch'=>'B-2025-008','expiry_date'=>'2026-10-01','days_left'=>34,'category'=>'Antibiotic','current_stock'=>30,'status'=>'Expiring Soon'],
    ];
}

// ============================================================
// RECENT PHARMACY ACTIVITY
// ============================================================
function getDemoRecentActivity(): array
{
    return [
        ['type'=>'verified','icon'=>'check-circle-2','color'=>'emerald','title'=>'Prescription Verified','message'=>'RX-2026-016 (Isosorbide Mononitrate) verified – drug interaction warning flagged.','time'=>'2 min ago'],
        ['type'=>'dispensed','icon'=>'pill','color'=>'blue','title'=>'Medicine Dispensed','message'=>'Clopidogrel 75mg dispensed to Rodrigo Morales (RX-2026-003).','time'=>'8 min ago'],
        ['type'=>'low_stock','icon'=>'triangle-alert','color'=>'amber','title'=>'Low-Stock Alert','message'=>'Paracetamol 500mg has fallen below minimum stock level (35/100 units).','time'=>'12 min ago'],
        ['type'=>'stock_in','icon'=>'package-plus','color'=>'teal','title'=>'Stock Received','message'=>'Ferrous Sulfate 325mg – Batch B-2026-025 received from Unilab (200 tablets).','time'=>'25 min ago'],
        ['type'=>'disposal','icon'=>'trash-2','color'=>'rose','title'=>'Disposal Recorded','message'=>'Cetirizine 10mg Batch B-2025-010 disposed (45 tablets, expired).','time'=>'1 hr ago'],
        ['type'=>'verified','icon'=>'check-circle-2','color'=>'emerald','title'=>'Prescription Verified','message'=>'RX-2026-009 (Mefenamic Acid) verified for Teresa May Aquino.','time'=>'1.5 hr ago'],
        ['type'=>'dispensed','icon'=>'pill','color'=>'blue','title'=>'Medicine Dispensed','message'=>'Insulin Glargine dispensed to Remedios Cabrera (RX-2026-025). Injection technique demonstrated.','time'=>'2 hr ago'],
        ['type'=>'rejected','icon'=>'x-circle','color'=>'rose','title'=>'Prescription Rejected','message'=>'RX-2026-030 (Cotrimoxazole) rejected – patient allergy to Penicillin cross-reactivity risk.','time'=>'3 hr ago'],
        ['type'=>'expiry','icon'=>'calendar-x','color'=>'orange','title'=>'Expiry Alert Triggered','message'=>'Vitamin C 500mg Batch B-2025-021 expiring in 15 days. Recommend expedited dispensing.','time'=>'4 hr ago'],
        ['type'=>'stock_in','icon'=>'package-plus','color'=>'teal','title'=>'New Inventory Batch','message'=>'Azithromycin 500mg – 100 tablets received from Pfizer Philippines.','time'=>'Yesterday'],
    ];
}

// ============================================================
// NOTIFICATIONS
// ============================================================
function getDemoNotifications(): array
{
    return [
        ['title'=>'New Prescription Received','message'=>'Dr. Michael Reyes submitted RX-2026-031 for Juan Dela Cruz. Awaiting verification.','type'=>'info','time'=>'Just now','unread'=>true,'action_link'=>'prescriptions'],
        ['title'=>'Low-Stock Alert','message'=>'Paracetamol 500mg has reached minimum stock level. Reorder required immediately.','type'=>'warning','time'=>'12 min ago','unread'=>true,'action_link'=>'alerts'],
        ['title'=>'Expiry Warning','message'=>'5 medicines are expiring within the next 30 days. Review expiry alerts.','type'=>'warning','time'=>'1 hr ago','unread'=>true,'action_link'=>'alerts'],
        ['title'=>'Prescription Requires Verification','message'=>'RX-2026-006 (Metformin – Crisanto Valenzuela) is awaiting pharmacist verification.','type'=>'info','time'=>'2 hr ago','unread'=>true,'action_link'=>'prescriptions'],
        ['title'=>'STAT Prescription – Urgent','message'=>'Dr. Mendoza submitted STAT prescription RX-2026-003 for Rodrigo Morales (ICU).','type'=>'critical','time'=>'3 hr ago','unread'=>false,'action_link'=>'prescriptions'],
        ['title'=>'Out of Stock – Salbutamol 2mg','message'=>'Salbutamol 2mg is now out of stock. Notify prescribing physician.','type'=>'critical','time'=>'4 hr ago','unread'=>false,'action_link'=>'inventory'],
        ['title'=>'Stock Successfully Received','message'=>'Ferrous Sulfate 325mg – 200 tablets received from Unilab (PO-2026-033).','type'=>'info','time'=>'Yesterday','unread'=>false,'action_link'=>'inventory'],
        ['title'=>'Disposal Record Created','message'=>'Expired Cetirizine 10mg (Batch B-2025-010) disposal completed and logged.','type'=>'info','time'=>'Yesterday','unread'=>false,'action_link'=>'inventory'],
    ];
}
